### ISSUE TITLE
keepalived-operator

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#107]
### Type of repository request

creation

### Requested name for the repository

keepalived-operator

### Repository Description

an operator to manage VIPs backed by keepalived

### Admin Access

raffaele spazzoli

### Additional details

Any additional information or context to provide for this request. Please also add
2. create the gh-pages branch
3. attach travis
4. create the deploy key

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by raffaelespazzoli** [comment]
can you also add the quay repo?

**Comment by sabre1041** [comment]
Repository created: https://github.com/redhat-cop/keepalived-operato
Registry created: https://quay.io/repository/redhat-cop/keepalived-operator

Would you be able to push code to the repository and then the remainder of the configuration can be completed.

**Comment by sabre1041** [comment]
This has been completed as requested
