### ISSUE TITLE
Change Permissions to automate-* or ansible related github projects

### ISSUE THREAD

**Issue by jlozadad** [redhat-cop/org#113]
### Organization or repository

all the repositories that start with automate* or have ansible in the title.

### Description of the issue

I don't have permissions to manage or update certain information such as description in automation related github projects. For example, I can't modify automate_elk

### Users or Teams affected

jlozadad/automation-cop-members

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by pabrahamsson** [comment]
@jlozadad it seems that `automate*` and `*ansible*` is a bit broad and will include repos that probably shouldn't be part of this request. Can you please update this issue with the exact names of the repos you would like to be included?

**Comment by jlozadad** [comment]
https://github.com/redhat-cop/automate_elk https://github.com/redhat-cop/automate-cicd https://github.com/redhat-cop/automate-tower https://github.com/redhat-cop/automate-exotic https://github.com/redhat-cop/automate-jcliff https://github.com/redhat-cop/automate-windows https://github.com/redhat-cop/agnosticd https://github.com/redhat-cop/infra-ansible https://github.com/redhat-cop/redhat_sso https://github.com/redhat-cop/k8s_config https://github.com/redhat-cop/jboss_webserver
