### ISSUE TITLE
businessautomation-cop

### ISSUE THREAD

**Issue by pamenon** [redhat-cop/org#117]
This is a business automation repo for all examples related to drools, jbpm, kogito, optaplanner etc.
### Type of repository request

Whether this request is a creation of a new repository, migration of existing repository, or deletion of a repository

### Requested name for the repository

Name of the repository to create or location of existing repository to migrate.

### Repository Description

Description applied to the newly created repository.

### Admin Access

Name of the team(s) and/or user(s) that should have admin access on the newly created repository.

### Write Access

Name of the team(s) and/or user(s) that should have write access on the newly created repository.

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@pamenon would you be able to provide responses to the question posed

**Comment by pamenon** [comment]
Type of repository request:
New repository
Requested name for the repository:
businessautomation-cop
Repository Description:
All examples related with business automation process such as jbpm, drools, optaplanner, kogito, quickstart, pipelines, etc.
Admin Access:
myself initially, I will add other CoP manager later.
Write and Read Access:
I will add users after as we need it.
Additional details:
We are create a centralise place for re useable examples, PoCs, standalone, spring boot, quarkus and openshift environment.

**Comment by sabre1041** [comment]
Repository created: https://github.com/redhat-cop/businessautomation-cop
