### ISSUE TITLE
New Team Project intializer

### ISSUE THREAD

**Issue by cnuland** [redhat-cop/org#120]
### Type of modification to a team
**New Team**

### Requested name for the team

project-initializer-team

### Team Description

Team working on the project-initializer operator 

### Membership

**Maintainers**
Christopher Nuland (cnuland)
Garrett Nekic (gnekic)
Andy Block (sabre1041)

**Members**
Maliat Manzur (mm7259)
John Tatman (otatman)

### Repositories
https://github.com/redhat-cop/org/issues/119
---

Review request:

cc: @redhat-cop/container-cop-core
       @sabre1041

**Comment by sabre1041** [comment]
Completed with #119
