### ISSUE TITLE
New Team Project Initializer Mergers

### ISSUE THREAD

**Issue by cnuland** [redhat-cop/org#121]
### Type of modification to a team

**New Team**

### Requested name for the team

project-initializer-team-mergers

### Team Description

A sub group of the project intitializer-team group that has the ability to manage merges

### Membership

Christopher Nuland (cnuland)
Garrett Nekic (gnekic)
Andy Block (sabre1041)

### Repositories
https://github.com/redhat-cop/org/issues/119

---

Review request:

cc: @redhat-cop/container-cop-core
       @sabre1041

**Comment by sabre1041** [comment]
Completed with #122
