### ISSUE TITLE
Migrate etsauer/onboarding-manager

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/org#13]
### Type of repository request

I would like to migrate the following repository into the CoP

https://github.com/etsauer/onboarding-manager

### Requested name for the repository

onboarding-manager

### Repository Description

Manages Creation of Namespaces in OpenShift

### Admin Access

Unsure, maybe just org maintainers.

### Write Access

container-cop-mergers

### Read Access

container-cop
gpte

### Additional details

None.

**Comment by sabre1041** [comment]
@etsauer has this been implemented via 9190cadaa857ddfb701f9458ae5b793a92a12295
