### ISSUE TITLE
getting added to the CoP trello

### ISSUE THREAD

**Issue by linuxstudio** [redhat-cop/org#132]
### Organization or repository

Container CoP trello board

### Description of the issue

I would like to get an invite for https://trello.com/redhatcop and possibly be added to the Container CoP team

### Users or Teams affected

Container CoP

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@linuxstudio Can you provide your Trello username and we will get you added.

Thanks,

**Comment by linuxstudio** [comment]
Hi @sabre1041 my username on Trello is francescominafra
Thanks!

**Comment by sabre1041** [comment]
@linuxstudio You should have access now.
