### ISSUE TITLE
egressip-ipam-operator repo creation request

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#133]
### Type of repository request

creation of a new repo

### Requested name for the repository

egressip-ipam-operator

### Repository Description

operator that automate the assignment of egress IP to openshift projects.

### Admin Access

raffaelespazzoli

### Write Access

trv-rpeoples

### Additional details

please hook up the following:
1. travis 
2. quay + quay credentials in travis
3. gh-pages + release key in travis

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
steps have been implemented
