### ISSUE TITLE
quay.io integration for babylon-events-console operator

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#140]
### Repository

https://github.com/redhat-cop/babylon-events-console

### Name of integration

quay.io

### Link to integration website

https://quay.io/repository/redhat-cop/babylon-events-console-operator

### Describe what is attempting to be accomplished

The next version of the babylon-events-console will split functionality between a web ui and an operator to maintain state. We wish to publish the operator image to https://quay.io/repository/redhat-cop/babylon-events-console-operator using github actions just like the UI at https://quay.io/repository/redhat-cop/babylon-events-console.

Hopefully this new build can use the same QUAY_USERNAME and QUAY_PASSWORD secret as used for the existing build.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by etsauer** [comment]
@jkupferer so I realized that the original babylon-events-console integration we set up was utilizing a generic `pushbot` account that we use across a bunch of unrelated repos. I'd like to get a bit more specific, but still give you and account you can use across related repos. Do you have an opinion on the name for this account so we can keep it straight. Sidenote: I noticed that there is a `poolboy` user linked to the poolboy repository in Quay as well... should all three of these use the same push account?

**Comment by jkupferer** [comment]
@etsauer I don't have an opinion on this. I wasn't aware of any of the details on how the accounts were configured.

**Comment by etsauer** [comment]
@jkupferer ok, I have created a new quay robot account calld `redhat-cop+babylon`, gave it write access to the following image repositories in quay.io/redhat-coop:

- babylon-events-console
- babylon-events-console-operator
- poolboy
- anarchy-runner
- anarchy-test-server
- anarchy

I've also added the robot account credentials as secrets in the following git repos:

- https://github.com/redhat-cop/anarchy
- https://github.com/redhat-cop/poolboy
- https://github.com/redhat-cop/babylon-events-console

Let me know if any of that isn't working properly and I can adjust it. Happy building!
