### ISSUE TITLE
New repo request - s2i-github-action

### ISSUE THREAD

**Issue by jacobsee** [redhat-cop/org#141]
### Type of repository request

Creation of a new repository

### Requested name for the repository

s2i-github-action

### Repository Description

Use Source-to-Image to build container images in a GitHub Action. 

### Admin Access

@redhat-cop/container-cop 

### Write Access

@redhat-cop/container-cop 

### Read Access

Everyone

### Additional details

This is a GitHub Action which can be imported into a GitHub workflow to do standard s2i builds of the repository it's running against. It then pushes the resulting image to a registry somewhere. Please see what I intend to push as a "first release" of this repository [HERE](https://github.com/jacobsee/s2i-github-action).

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
@jacobsee we had a quick discussion on this in the CoP, and we are leaning towards having a single repo for multiple github-action functionalities. We are thinking calling this repo just `github-actions` and in there you can add a `s2i` folder that will basically generate the necessary image in quay.io, etc. Are you ok with this plan? If so, we'll get this processed and added ASAP.

**Comment by jacobsee** [comment]
Yes, sounds good to me 👍
