### ISSUE TITLE
trello access

### ISSUE THREAD

**Issue by aglenn360** [redhat-cop/org#148]
### Organization or repository

cop trello board

### Description of the issue

I tried joining the container cop trello board some time ago and never managed to get it working, I have changed my profile now and was wondering if it would be possible when you got chance to provide me access.

my account in trello is now 

Alex Glenn
@alexglenn3

### Users or Teams affected

Alex Glenn
@alexglenn3

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Access has been granted
