### ISSUE TITLE
Migration of python-kopf-s2i and python-kopf-s2i-example repositories

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#151]
### Type of repository request

migration of existing repository

### Requested name for the repository

https://quay.io/repository/jkupferer/python-kopf-s2i -> redhat-cop/python-kopf-s2i

https://quay.io/repository/jkupferer/python-kopf-s2i-example -> redhat-cop/python-kopf-s2i-example

### Repository Description

The python-kopf-s2i repository creates a source-to-image builder for the Python kopf operator framework.

https://kopf.readthedocs.io/en/latest/

The python-kopf-s2i-example repository is an example of how to use the source-to-image.

The s2i scripts have been tested and are compatible with odo, which should allow for a variety of IDE integrations for python operator development with kopf.

### Admin Access

The babylon team.

### Write Access

none

### Read Access

none

### Additional details

These repositories also will need quay.io integration. This can be requested in a separate issue...

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by etsauer** [comment]
Hey @jkupferer I'm not seeing any source code included in this request. Either way, it looks to me like this would fit nicely in the [container-quickstarts] repo. We keep several other custom s2i images there.  That repo also already contains a secret config for pushing images to quay, so we then just need to create the image repositories.

If you want to go ahead and work on the PR for that repo, I will get the image repository.

I'm also a bit confused about the difference between python-kopf-s2i and python-kopf-s2i-example. Can you elaborate?

**Comment by jkupferer** [comment]
I can switch this to a PR to container-quickstarts, just need to figure out how to add that there.

python-kopf-s2i is the base s2i builder image while python-kopf-s2i-example is an example repository showing how to use python-kopf-s2i.

**Comment by jkupferer** [comment]
The PR has been merged to container-quickstarts, but it seems either the python-kopf-s2i repository does not exist or permissions are not configured for the robot account:
https://github.com/redhat-cop/containers-quickstarts/runs/691145587?check_suite_focus=true

**Comment by jkupferer** [comment]
All set on this! :D
