### ISSUE TITLE
Please add me as a member of the redhat-cop organization

### ISSUE THREAD

**Issue by erouvas** [redhat-cop/org#155]
Hi,

this is erouvas (erouvas@redhat.com)

I would like to become a general contributor to the Red Hat Communities of Practice GitHub Organization.

I'm interested in contributing to https://github.com/redhat-cop/businessautomation-cop.

Thanks.
---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
Done as part of PR #156
