### ISSUE TITLE
tower_grafana_dashboards

### ISSUE THREAD

**Issue by leoaaraujo** [redhat-cop/org#157]
### Type of repository request

Whether this request is a creation of a new repository, migration of existing repository, or deletion of a repository

A: New Repository

### Requested name for the repository

Name of the repository to create or location of existing repository to migrate.

A: ansible-tower-grafana-dashboards

### Repository Description

Description applied to the newly created repository.

A:  Playbook for installing node_exporter on rhel8 and dashboards to import into Grafana and monitor Ansible Tower metrics.

### Admin Access

Name of the team(s) and/or user(s) that should have admin access on the newly created repository.

A: leoaaraujo

### Write Access

Name of the team(s) and/or user(s) that should have write access on the newly created repository.

A: leoaaraujo

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

A leoaaraujo

### Additional details

Any additional information or context to provide for this request.

A: the link to this repository will be made available in an article that will be published on the ansible blog to download the dashboards and playbook.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by liquidat** [comment]
@jlozadad Any chance that we can create the repo?

**Comment by sabre1041** [comment]
Repository has been created as requested

**Comment by leoaaraujo** [comment]
Thanks @sabre1041 and @liquidat
