### ISSUE TITLE
Create repository for osia tool

### ISSUE THREAD

**Issue by mijaros** [redhat-cop/org#159]
### Type of repository request

New repository.

### Requested name for the repository

redhat-cop/osia

### Repository Description

OpenShift Infrastructure Automation

Tool for reliable automated deployments of OpenShift Container Platform 4.x into OpenStack and AWS.

### Admin Access

mijaros

### Write Access

None

### Read Access

Everyone - the repository should be public.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repository created a requested
