### ISSUE TITLE
quay repo for signing service

### ISSUE THREAD

**Issue by jgoldsmith613** [redhat-cop/org#163]
### Repository

Name of the repository within the organization to integrate with an external system.
https://github.com/redhat-cop/image-scanning-signing-service

### Name of integration

Name of the external system or tool (Example: Travis)
quay

### Link to integration website

Reference to the integration (Example: https://travis-ci.org/)
quay.io

### Describe what is attempting to be accomplished

A clear and concise description of what is trying to be accomplished with this integration.

Place to put images so users do not have to build from scratch

### Additional context for request

Any additional information or context to describe the use case.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Quay repository created

https://quay.io/repository/redhat-cop/image-scanning-signing-service?namespace=redhat-cop
