### ISSUE TITLE
signing pod quay repo

### ISSUE THREAD

**Issue by jgoldsmith613** [redhat-cop/org#165]
### Repository

Name of the repository within the organization to integrate with an external system.
image-scanning-signing-service

### Name of integration

Name of the external system or tool (Example: Travis)
quay
### Link to integration website

Reference to the integration (Example: https://travis-ci.org/)
quay.io

### Describe what is attempting to be accomplished
need repo for signing pod too

A clear and concise description of what is trying to be accomplished with this integration.

### Additional context for request
call the repo image-signer

Any additional information or context to describe the use case.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repository created as requested:

https://quay.io/repository/redhat-cop/image-signer
