### ISSUE TITLE
Create a automate_tower_demo repository

### ISSUE THREAD

**Issue by jlozadad** [redhat-cop/org#17]
### Type of repository request

new repository

### Requested name for the repository

automate_tower_demo

### Repository Description

Automation content for Ansible Tower to use to spin it up in containers and other future platform. This includes LDAP connections.

### Admin Access

jlozadad

### Write Access

jlozadad

### Read Access

jlozadad

**Comment by sabre1041** [comment]
Repository added and permissions granted
