### ISSUE TITLE
Requesting redhat-cop quay.io access permission

### ISSUE THREAD

**Issue by aizuddin85** [redhat-cop/org#176]
### Type of permission change

CoP quay.io membership

### Requested Changes

Request to access redhat-cop for my quay.io user "mzali"

### Additional details

Requesting access so we can provide prebuilt image for [this integration](https://github.com/redhat-cop/tool-integrations/tree/master/alertmanager-notifier-gateway)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@aizuddin85 ; if you follow this PR, you don't need access to quay directly:
- https://github.com/redhat-cop/redhat-cop.github.io/pull/12

@pabrahamsson will be able to correct me, if that's wrong tho :)

**Comment by aizuddin85** [comment]
> @aizuddin85 ; if you follow this PR, you don't need access to quay directly:
> 
>     * [redhat-cop/redhat-cop.github.io#12](https://github.com/redhat-cop/redhat-cop.github.io/pull/12)
> 
> 
> @pabrahamsson will be able to correct me, if that's wrong tho :)

Thanks @garethahealy , found this https://redhat-cop.github.io/ci/publishing-images.html. Let me try this action workflow mentioned in the docs.

**Comment by pabrahamsson** [comment]
@aizuddin85 you can use either the document you found or what's in the PR mentioned by @garethahealy. The intent is that the PR will replace what's in the document you found as it is a bit more flexible in how you manage when your image is built. It also uses the newly (ish) released Docker GH action for building and pushing.
I'm closing this issue but feel free to re-open if you think the Quay access is necessary.
