### ISSUE TITLE
Permissions to create new repositories for AppDev CoP

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/org#18]
### Type of permission change

Permissions to create new repositories for the AppDev CoP

### Requested Changes

Permissions to create new repositories for the AppDev CoP

### Additional details

Ideally, we would like to manage this using Teams. The **AppDev CoP/committers** team would have this permission and the contributors sub-team would not.

**Comment by sabre1041** [comment]
@InfoSec812 repository creation permissions in the org cannot be managed in that level of granularity. Creation of repositories should continue to managed through this repository and the CoP request process
