### ISSUE TITLE
Disable quay.io build for anarchy and poolboy

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#184]
### Repository

anarchy and poolboy

### Name of integration

quay.io

### Describe what is attempting to be accomplished

These repositories are moving to build/push using GitHub actions. All the preparation work for GitHub actions has been done, but the existing quay.io build triggers need to be disabled to prevent competing mechanisms from push images.
---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by etsauer** [comment]
@jkupferer disabled the build trigger in Quay.io for redhat-cop/anarchy. For poolboy, it doesn't look like anything was ever set up for building.
