### ISSUE TITLE
Creation of new repository

### ISSUE THREAD

**Issue by josecastillolema** [redhat-cop/org#190]
### Type of repository request

Migrate repository

### Requested name for the repository

https://github.com/josecastillolema/aodh2sensu

### Repository Description

A service to import OpenStack Aodh alarms into Sensu Core Server.

### Admin Access

@josecastillolema 

### Write Access

-

### Read Access

@all

### Additional details

I have created a service to import OpenStack Aodh alarms into Sensu Core Server, I believe it may add value to the redhat-cop org.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@josecastillolema do you have other contributors who are actively working on this project?

**Comment by josecastillolema** [comment]
hi @sabre1041 ! 
I have developed the proxy alongside @leoaaraujo for a 3-year telco project that ends in 2022.
We are not actively working on it anymore as it has passed the initial validations proofs.
thanks,

**Comment by garethahealy** [comment]
@josecastillolema ; as no further development of this repo is planned from your side, am not sure what benefit it would bring to move it into the CoP, as if we have no active maintainers for it, it will simply be archived.
