### ISSUE TITLE
Request two new repos in redhat-cop

### ISSUE THREAD

**Issue by aizuddin85** [redhat-cop/org#199]
### Type of repository request

Two new repositories for https://github.com/redhat-cop/tool-integrations/pull/21.

### Requested name for the repository
1. quay.io/redhat-cop/alertmanager-telegram-gateway
2. quay.io/redhat-cop/alertmanager-line-gateway

### Repository Description
Alertmanager gateway for 3rd party receiver.

### Admin Access

1. aizuddin85
2. tool-integrations

### Write Access

1. aizuddin85
2. tool-integrations

### Read Access

Public.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repositories created

@aizuddin85 can you elaborate on `tool-integrations`. This is a repository. We can create a new team that can provide access to a set of users

**Comment by aizuddin85** [comment]
@sabre1041 I was referring tools-integration as a team for the RW  image repo rights if the team exists. if not exist, shall we create and use team of users instead of assigning to a particular user?

@oybed any thoughts?

**Comment by aizuddin85** [comment]
@sabre1041 i think there are some confusion regarding this request.i probably raised a wrong issue for the request. what im trying to request is new quay.io/redhat-cop image repo to store built image from tools-integration GH actions that looks like these.

1. quay.io/redhat-cop/alertmanager-telegram-gateway
2. quay.io/redhat-cop/alertmanager-line-gateway

**Comment by sabre1041** [comment]
@aizuddin85 no team currently exists. We can create one if you would like. Please provide quay.io usernames and allocate the permissions to them

**Comment by aizuddin85** [comment]
@sabre1041 at this stage i think it just me who need the quay.io access for these fresh image repos. my quay.io username is `mzali`.
