### ISSUE TITLE
Create the following repositories.

### ISSUE THREAD

**Issue by jlozadad** [redhat-cop/org#203]
### Type of repository request

 Create a list of repositories.

### Requested name for the repository

Hardware_automation_collection
Cloud_provision_automation_collection
Molecule_cicd_automation

### Repository Description

Hardware automation collection that includes bios, racks, and remote management.

Cloud automation provision that includes working with rhv, satellite and idm. Also includes configuring provisioned systems

Molecule collection that can be used for testing roles, give examples and keep a standard molecule files that can be easily followed.

### Admin Access

Jlozadad

### Write Access

Jlozadad
### Read Access

jlozadad

### Additional details

This repositories will be used for the upcoming working or interest groups. We have specific goals with different use cases that we want to tackle.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@jlozadad Since you mentioned that there would be multiple members collaborating in these repositories, do you want to include an existing team or create a team to manage access?

**Comment by jlozadad** [comment]
Couldn't see if there was a team but a automation-cop team would be fine.

**Comment by sabre1041** [comment]
@jlozadad repositories created.

What role do you want to be applied to the `automation-cop` team?

**Comment by jlozadad** [comment]
developers.

**Comment by sabre1041** [comment]
@jlozadad these are the valid permission types:

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization

**Comment by oybed** [comment]
@jlozadad any thoughts on the permissions here?

**Comment by jlozadad** [comment]
I apologize for taking a while to respond. Maintain permissions.
