### ISSUE TITLE
Add repositories for AppDev CoP Workshop Content

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/org#21]
### Type of repository request

We would like to migrate all repositories from https://github.com/rhoar-qcon-2018 under the CoP for collaboration by members of the AppDev CoP. 

### Requested name for the repository

rhoar-workshop

### Repository Description

This collection of repositories represent a series of microservices built using the RHOAR tools. The content combines to form a workshop lab which allows attendees to experience development of Microservices Architecture (MSA) systems on OpenShift using CI/CD tooling automated with Ansible.

### Admin Access

The AppDev CoP committers should have admin access

### Write Access

The AppDev CoP committers should have write access

### Read Access

All AppDev CoP members

### Additional details

N/A

**Comment by sabre1041** [comment]
completed with #118
