### ISSUE TITLE
create acm-policies repo

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#214]
### Type of repository request

creation

### Requested name for the repository

acm-policies

### Repository Description

Curated set of policies for ACM

### Admin Access

Raffaele Spazzoli
Daniel Trieu

### Write Access

Raffaele Spazzoli
Daniel Trieu

### Read Access

?? Isn't this going to be public?
so I guess the answer is `all`

### Additional details

none

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@raffaelespazzoli did you want a team to be created instead of individual users?

**Comment by raffaelespazzoli** [comment]
no sure. is it possible to keep these two users for now and add a team later? @sabre1041

**Comment by sabre1041** [comment]
@raffaelespazzoli not a problem. what is Daniel Trieu's GitHub username?

**Comment by garethahealy** [comment]
@raffaelespazzoli ; do you have some examples of what the policies look like? just wondering if there's any cross over with the policies we're adding into:
- https://github.com/redhat-cop/rego-policies

**Comment by raffaelespazzoli** [comment]
@garethahealy I don't have any examples. They are called policies, but I suspect they are just regular kube resources to do day 2 configuration. certainly they are not rego policies.

**Comment by dtrieu80** [comment]
@sabre1041 Hey Andy, this is me.
This repo will be used as part of a workshop. The participants are not known right now. When I get a list of them, I will make sure they have github accounts to contribute. However, I do not wish to bother you about perms to this repo.

@garethahealy As Raffa stated, these are not rego policies, but policies designed in RHACM. They may overlap in purpose.

**Comment by sabre1041** [comment]
@raffaelespazzoli @dtrieu80 Repository created and permissions set. Let me know when its good to close this issue

**Comment by sabre1041** [comment]
closing as all tasks have been completed
