### ISSUE TITLE
Please provide repository write permissions. 

### ISSUE THREAD

**Issue by ally-jarrett** [redhat-cop/org#218]
### Type of permission change

Type of permissions change that is being requested (Example: Team membership, repository membership)

### Requested Changes

Description of the changes requested

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@ally-jarrett can you provide the type of write permission that you are seeking

**Comment by garethahealy** [comment]
think this can be closed, as it was solved via: https://github.com/redhat-cop/org/pull/225

@ally-jarrett ?

**Comment by sabre1041** [comment]
Closed via #225
