### ISSUE TITLE
Please add me as a member flow

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/org#224]
A few people have messaged me asking why when they request to be added to the org, the following happens:

- they get an email saying you've been added
- a few hours later, they get an email saying they've been deleted
- then a few more, once the PR is merged, they have access

I presume this is because of how the automation is running, i.e.: to test it, its executed for real.

Can this be tweaked? or if not, at least called out/documented to stop confusion?

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@garethahealy the CoP SRE team made a few adjustments recently. Please let us know if the end user experience has improved as a result
