### ISSUE TITLE
Create new GitHub repo for alertmanager integration.

### ISSUE THREAD

**Issue by aizuddin85** [redhat-cop/org#226]
### Type of repository request
This request is about requesting new redhat-cop github repository to host alertmanager-integration.

### Requested name for the repository

alertmanager-integration

### Repository Description

Repository for various alertmanager integration like 3rd party webhook integration.

### Admin Access
1.  `alertmanager-integration` team
2. `aizuddin85` user

### Write Access
1.  `alertmanager-integration` team
2. `aizuddin85` user

### Read Access
1.  `alertmanager-integration` team
2. `aizuddin85` user

### Additional details

Currently code are hosted on https://github.com/redhat-cop/tool-integrations/, going to move those alertmanager integration related integration to this newly created github repo. 

We have one customer in Thailand are using  https://github.com/redhat-cop/tool-integrations/tree/master/alertmanager-notifier-gateway/alertmanager-line-gateway in the production env.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@aizuddin85 Can you elaborate on the need for a separate repository?

**Comment by aizuddin85** [comment]
> @aizuddin85 Can you elaborate on the need for a separate repository?

I`m thinking of hosting alertmanager integration into its own repository for repo visibilty and also grow from there.  But I have no problem to stay on current repo as well.

**Comment by sabre1041** [comment]
Let's hold off on a separate repository until you feel that is has a large contributor and/or adoption

**Comment by aizuddin85** [comment]
@sabre1041 fair enough, i'll resubmit when we have more contribution or adoption. thanks.
