### ISSUE TITLE
Please create a repo for global-load-balancer-operator

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#228]
### Type of repository request

creation of `global-load-balancer-operator`

### Requested name for the repository

`global-load-balancer-operator`

### Repository Description

A global load balancer operator for OpenShift

### Admin Access

raffaele.spazzoli

### Read Access

public repo

### Additional details

please add a github pages branch and corresponding quay.io repo with credentials.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
GitHub and Quay repositories created. GitHub secrets added for access to Quay
