### ISSUE TITLE
🦄 Transfer a repo to the cop-org as per previous cop call 🔥

### ISSUE THREAD

**Issue by springdo** [redhat-cop/org#237]
### Type of repository request

migration of the https://github.com/rht-labs/helm-charts repo to cop world.

### Requested name for the repository

`helm-charts`

### Repository Description

`This is the Helm Chart repository of the Red Hat CoP 🐙⚓️`

### Admin Access

yes please :)

Name of the team(s) and/or user(s) that should have admin access on the newly created repository.

The current maintainers in the labs namespace should be given admin access in this repo at least so they can approve PRs and monitor the ci process etc. 
- [ ] @ckavili 
- [ ] @eformat 
- [ ] @tylerauerbeck
- [ ] @gsampaio-rh
- [ ] @jtudelag
- [ ] @springdo 

### Write Access

Name of the team(s) and/or user(s) that should have write access on the newly created repository.

The current contributors in the labs namespace should be given write access in this repo so they can continue to contribute as they previously could
- [ ] @garethahealy 
- [ ] @mvmaestri
- [ ] @jijiechen

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

### Additional details

Request discussed in CoP meeting a few weeks ago. Following up .... 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by etsauer** [comment]
We made a decision in chat the other day that we can reuse the @redhat-cop/day-in-the-life teams for RBAC.

**Comment by springdo** [comment]
Hi @etsauer! 👋 How's it going? 
Not sure that was what was _agreed_ in the chat the other day as no one responded to my comment challenging it .... but anyways, if you want to reuse the team that's fine as long as we update it so the people listed above _who currently can write to the repo_ are still able to. What is the process in CoP land for updating that team so the above read / write permissions can be achieved? Once that's done we can transfer the repo etc

FYI - @eformat @tylerauerbeck @ckavili @jtudelag

**Comment by sabre1041** [comment]
@springdo Created #243 to add members to @redhat-cop/day-in-the-life

I'll be owning the migration of the repository. Please reach out and we can work together on the transfer into the CoP org

**Comment by springdo** [comment]
just need to get the org stuff sorted for merge rights but the repo transfer is complete. https://github.com/redhat-cop/helm-charts

**Comment by sabre1041** [comment]
Repository has been migrated
