### ISSUE TITLE
Resource Dispatcher Quay Repo

### ISSUE THREAD

**Issue by jacobsee** [redhat-cop/org#239]
### Type of repository request

Quay image repository

### Requested name for the repository

resource-dispatcher

### Repository Description

Repository for built images of https://github.com/redhat-cop/tool-integrations/tree/master/resource-dispatcher

### Admin Access

Access is set up in https://github.com/redhat-cop/org/pull/238

### Write Access

Access is set up in https://github.com/redhat-cop/org/pull/238

### Read Access

Public - everyone should have read access

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Resolved by #238
