### ISSUE TITLE
Creation of tower_utilities repository

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/org#240]
### Type of repository request

Creation of tower_utilities repository

### Requested name for the repository

tower_utilities

### Repository Description

Ansible Collection for roles and other objects for general use with Tower

### Admin Access

@redhat-cop/automation-cop-mgrs

### Write Access

@redhat-cop/automation-cop-members

### Read Access

all

### Additional details

n/a

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@Tompage1994 Are you planning on an integration with Ansible Galaxy?

**Comment by Tompage1994** [comment]
Yes, this is part of the tower automation working group and we aim to create another collection which will be published to galaxy similar to the tower_configuration repo

**Comment by sabre1041** [comment]
@Tompage1994 Repository created and Ansible Galaxy API key added as a secret.

Permissions will be applied when [this](https://github.com/redhat-cop/org/pull/250) is merged.
