### ISSUE TITLE
New Repository Request

### ISSUE THREAD

**Issue by jameslabocki** [redhat-cop/org#256]
### Type of repository request

Creation of a new repository

### Requested name for the repository

openshift-migration-best-practices

### Repository Description

best practices guide for migrating between OpenShift 3 and OpenShift 4

### Admin Access

jameslabocki
apinnick
mwitzenm

### Write Access

Name of the team(s) and/or user(s) that should have write access on the newly created repository.

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

### Additional details

Thank you

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repository created 

https://github.com/redhat-cop/openshift-migration-best-practices
