### ISSUE TITLE
New repository for custom-metering

### ISSUE THREAD

**Issue by ianwatsonrh** [redhat-cop/org#267]
### Type of repository request

New repository, mirror of https://gitlab.consulting.redhat.com/iwatson/custom-metering

### Requested name for the repository

custom-metering or something similar

### Repository Description

Details how to extend the openshift-metering capability. Labels are added onto a namespace such as budget_code which is then aggregated in the metering reports.

### Admin Access

Ian Watson

### Write Access

containers cop team

### Read Access

All

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
Hi @ianwatsonrh - do you want the original repo transferred to the redhat-cop space? (and hence have the old link redirect to the new cop based repo)? If so, please give me access to the original repo and I can help transfer it to the cop space.

**Comment by ianwatsonrh** [comment]
Yes, but the repository is already set to internal.

So not sure why you can’t access it. I can copy it over myself once the repo is created.

**Comment by garethahealy** [comment]
@ianwatsonrh ; as `openshift-metering` is now deprecated, am not sure if there's any benefit of bringing this repo into the CoP.
