### ISSUE TITLE
add the following repositories under management of the team automation-cop-members

### ISSUE THREAD

**Issue by jlozadad** [redhat-cop/org#27]
### Type of modification to a team

modification of automation-cop-members

### Requested name for the team

automation-cop-members

### Team Description

Members of the Automation Community Of Practice

### Team Parent

N/A

### Membership

N/A no change.

### Repositories

https://github.com/redhat-cop/automate-cicd
https://github.com/redhat-cop/automate-tower-ha-dr
https://github.com/redhat-cop/automate-tower
https://github.com/redhat-cop/automate-jcliff
https://github.com/redhat-cop/automate-exotic
https://github.com/redhat-cop/automate-windows
https://github.com/redhat-cop/automate_tower_genie_collections
https://github.com/redhat-cop/automate_tower_lab
https://github.com/redhat-cop/infra-ansible
https://github.com/redhat-cop/automate-tower
https://github.com/redhat-cop/redhat_sso
https://github.com/redhat-cop/jboss_webserver

**Comment by sabre1041** [comment]
Completed as per #32
