### ISSUE TITLE
new repo: volume-expander-operator

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#283]
### Type of repository request

creation of new repository

### Requested name for the repository

volume-expander-operator

### Repository Description

operator to automatically expand PVCs.

### Admin Access

Raffaele Spazzoli

### Write Access

Raffaele Spazzoli

### Read Access

Raffaele Spazzoli

### Additional details

N/A

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Please share list of existing repository along with contributors working on the project

**Comment by raffaelespazzoli** [comment]
no existing repos, no other collaborators.

**Comment by sabre1041** [comment]
Recommend incubating the project in a personal repository until either a group of contributors has been established and/or a need from the community arises

**Comment by raffaelespazzoli** [comment]
the need has arisen in one of my customers. and it's such a general and obvious use case that it's surprising that someone has not done this. It's hard to see how a community can form around a personal repo. Anyway here it is: https://github.com/raffaelespazzoli/volume-expander-operator

**Comment by raffaelespazzoli** [comment]
please create the corresponding quay repo and add the quay credentials as secret:
`QUAY_USERNAME`
`QUAY_PASSWORD`
