### ISSUE TITLE
ah_configuration repository creation

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/org#293]
### Type of repository request

New Repository

### Requested name for the repository
ah_configuration

### Repository Description
Collection of modules and roles to configure Automation Hub

### Admin Access

@sean-m-sullivan 
@redhat-cop/automation-cop-mgrs

Write Access

@redhat-cop/automation-cop-members

### Additional details

Will clone this [temp repo](https://github.com/sean-m-sullivan/galaxy_collection_temp), to the redhat_cop for use and start getting contributors to work in creation. The Linked repo currently is a MVP that has a module that creates namespaces in galaxy_ng.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sean-m-sullivan** [comment]
@sabre1041 Possible for you to handle this, or assign to someone? Thanks

**Comment by sabre1041** [comment]
@sean-m-sullivan Would you like this repository be associated to an existing team?

**Comment by sean-m-sullivan** [comment]
Updated to include teams cloned from the previous ones we've created around tower.
