### ISSUE TITLE
New repository - automation-good-practices

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/org#295]
### Type of repository request

new repository

### Requested name for the repository

automation-good-practices

### Repository Description

Recommended practices for all elements of automation using Ansible, starting with collections and roles, continuing with playbooks, inventories and plug-ins... These good practices are planned to be used by all Red Hat teams interested but can of course be used by others.

### Admin Access

automation-cop-mgrs

### Write Access

automation-cop-members

### Read Access

everybody

### Additional details

Not really relevant, but FYI, we plan to start from https://github.com/oasis-roles/meta_standards/blob/master/README.md and improve/expand on it.

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@ericzolf "good practices" sounds a little odd

Does `automation-recommended-practices` or `automation-best-practices` appeal instead?

**Comment by ericzolf** [comment]
You're the native speaker, but legal doesn't like best practices so I try to avoid the term. I found a lot of [good practices](https://en.wikipedia.org/wiki/Good_practice) on the web, and it's shorter than "recommended practices", but I can also live with recommended practices. Perhaps good practice (singular)?
You decide!
