### ISSUE TITLE
New Repository - disconnectedinfra

### ISSUE THREAD

**Issue by hfenner** [redhat-cop/org#297]
### Type of repository request
Create a new repository

### Requested name for the repository
disconnectedinfra

### Repository Description
Ansible collection designed to support building a disconnected network in a connected world.

### Admin Access
cyberinfrasig
hfenner

### Write Access
None

### Read Access
Everyone

### Additional details
* There is existing content for this repo, but creating a new repo to start fresh is fine
* The team cyberinfrasig does not exists yet, there is an issue in to create it #298 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by pabrahamsson** [comment]
Resolved by #301
