### ISSUE TITLE
New Team - cyberinfrasig

### ISSUE THREAD

**Issue by hfenner** [redhat-cop/org#298]
### Type of modification to a team

Creation of new team

### Requested name for the team

cyberinfrasig

### Team Description

Cyber Infrastructure Special Interest Group

### Team Parent

N/A

### Membership

hfenner - maintainer

### Repositories

None (Issue currently exists to create disconnectedinfra #297 )

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by pabrahamsson** [comment]
Resolved by #301
