### ISSUE TITLE
admin access to repository, or greater access

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/org#302]
### Organization or repository
[tower_configuration](https://github.com/redhat-cop/tower_configuration)
[tower_utilities](https://github.com/redhat-cop/tower_utilities)
[tower_configuration_examples](https://github.com/redhat-cop/tower_configuration_examples)
[ah_configuration](https://github.com/redhat-cop/ah_configuration)

### Description of the issue
Had noticed when [ah_configuration ](https://github.com/redhat-cop/ah_configuration) was created, I was given the ability to change settings including actions/secrets in that repository. Would like myself and another admin to be given the privileged access in the other two repositories we help maintain. [Was this PR](https://github.com/redhat-cop/org/pull/294/files), but not sure what specifically is different compared to the other two.

The purpose of this would be to be able to create/maintain secrets, and create our own self-hosted runners that would embed on an openshift cluster for deploying tests. 

### Users or Teams affected
@sean-m-sullivan
@tompage1994

### What needs to be created
Request would be to create a team of tower_admins that have admin access to the above repositories. 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sean-m-sullivan** [comment]
@sabre1041 Possible for you to handle this, or assign to someone? Thanks

**Comment by sabre1041** [comment]
@sean-m-sullivan the CoP is attempting to avoid individual users with specific rights to a repository and instead leveraging GitHub teams from a management point. 

For example, do we want to use an existing team (such as automation-cop-mgrs) or create a new team?

**Comment by sean-m-sullivan** [comment]
I understand that, I'm thinking of a tower team? automation-cop-tower-mgrs perhaps? Would put Tom and I in that group to manage the 3 tower repos and the AH repo. Actual goal was to make changes to how we do tests and the runners over the holidays without pinging you guys, and/or copying a Personal access token from someone to setup said runners.
