### ISSUE TITLE
operator-utils : maintenance

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#304]
### Type of repository request

various

### Requested name for the repository

operator-utils

### Additional details

Please create the following repos on quay:
quay.io/redhat-cop/operator-utils
quay.io/redhat-cop/operator-utils-bundle

Please add the variables to the operator-utils
QUAY_USERNAME
QUAY_PASSWORD
with an account that can push images to the previous repos.

Please create the `gh-pages` branch

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@raffaelespazzoli can we rename `quay.io/redhat-cop/operator-utils-controller-bundle` to `quay.io/redhat-cop/operator-utils-controller-bundle` to align with best practices of the operator naming?

**Comment by raffaelespazzoli** [comment]
The names look the same, what did you mean?

**Comment by sabre1041** [comment]
@raffaelespazzoli copy/paste error. fixed

**Comment by raffaelespazzoli** [comment]
updated the comment and changed the code.

**Comment by sabre1041** [comment]
Necessary requests have been completed
