### ISSUE TITLE
[must-gather-operator] maintenance

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#308]
### Type of repository request

maintenance

### Requested name for the repository

must-gather-operator

### Additional details

Please add the following github secrets
QUAY_USERNAME
QUAY_PASSWORD

with push grants to the following quay repo (create them if necessary):
quay.io/redhat-cop/must-gather-operator
quay.io/redhat-cop/must-gather-operator-bundle

these repos should be public.

Finally disconnect travis and any permission that it holds against this repo.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Resolved by #311
