### ISSUE TITLE
Add Org Secret to ah_configuration

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/org#317]
### Organization or repository

redhat-cop/ah_configuration

### Description of the issue

Need ANSIBLE_GALAXY_APIKEY key.
Would like to publish initial version of the collection, and would need this key to do so. tower_utilities and tower_configuration already have this key. 

### Users or Teams affected

redhat-cop/ah_configuration

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sean-m-sullivan** [comment]
@sabre1041 @oybed  Possible for one you to handle this, the collection is ready for its first release, Thanks

**Comment by sabre1041** [comment]
@sean-m-sullivan Secret has been added. Apologies for the delay
