### ISSUE TITLE
[microsegmentation operator] retire repo

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#318]
### Type of repository request

delete https://github.com/redhat-cop/microsegmentation-operator

### Requested name for the repository

https://github.com/redhat-cop/microsegmentation-operator

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
@raffaelespazzoli I've archived this repo - please let us know if you'd rather have it deleted per your request.
https://github.com/redhat-cop/microsegmentation-operator

**Comment by garethahealy** [comment]
@raffaelespazzoli ; can this be closed?
