### ISSUE TITLE
Quay.io repository for babylon-admin

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#355]
### Repository

https://github.com/redhat-cop/babylon

### Name of integration

quay.io

### Link to integration website

https://quay.io/organization/redhat-cop

### Describe what is attempting to be accomplished

We would like to setup container image build automation for the babylon repository to build and push an image for a babylon administration interface as quay.io/redhat-cop/babylon-admin.

We would like to follow the pattern to build the image used by anarchy:

https://github.com/redhat-cop/anarchy/blob/main/.github/workflows/publish.yaml

Using a quay.io robot account with access configured through GitHub secrets:

- REGISTRY_URI
- REGISTRY_REPOSITORY
- REGISTRY_USERNAME
- REGISTRY_PASSWORD

We need the quay.io repository created, a robot configured with write access, and secrets created in the babylon github repo with the above.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@jkupferer Repository created along with robot account credentials as secrets
