### ISSUE TITLE
aws-sq-exporter quay repository

### ISSUE THREAD

**Issue by jfilipcz** [redhat-cop/org#379]
### Repository

https://github.com/redhat-cop/monitoring/

### Name of integration

quay.io

### Link to integration website

https://quay.io/organization/redhat-cop

### Describe what is attempting to be accomplished

Create quay.io repositories for: https://quay.io/repository/redhat-cop/aws-sq-exporter

### Additional context for request

This is to enable docker image push to quay.io for newly created aws-sq-exporter

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
@jfilipcz as the other monitoring quay.io repos have the prefix of `monitoring-`, I'd like to propose that we name this one `monitoring-aws-sq-exporter`. Let me know if you're good with this.

**Comment by jfilipcz** [comment]
Yes I am, no problem with that
