### ISSUE TITLE
New Repository for Classroom Antora Logic

### ISSUE THREAD

**Issue by varodrig** [redhat-cop/org#383]
Type of repository request
I need a new repository

Requested name for the repository
classroom-content

Repository Description
Classroom is a new project for workshops/labs creation.
This new project will be replacing homeroom/bookbag.
Classroom Content will be in charge of content lab image generation including Antora's logic.

Admin Access
Valentina Rodriguez Sosa,varodrig@redhat.com

Wolfgang Kulhanek,wkulhane@redhat.com

team that we can associate with the request
GPTE Team

Read Access
Name of the team(s) and/or user(s) that should have read access on the newly created repository.

Additional details
Any additional information or context to provide for this request.

https://docs.google.com/document/d/10P5JDMXwp6uynMWhrfGayB6tisUyMnhq_SrL_qOZyUY/edit

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@varodrig ; any update on @oybed suggestion (https://github.com/redhat-cop/org/issues/382#issuecomment-885898197)?

**Comment by sabre1041** [comment]
@garethahealy @varodrig is this still a valid issue ?

**Comment by sabre1041** [comment]
Closing issue as it is no longer needed
