### ISSUE TITLE
Migrate babylon_anarchy_governor Repository

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#389]
### Type of repository request

Migration of existing repository

### Requested name for the repository

https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor

### Repository Description

Ansible role implementing core logic for Babylon processing within Anarchy.

### Admin Access

babylon-admin

### Write Access

babylon

### Read Access

Public read access

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@jkupferer ; is this still needed?
