### ISSUE TITLE
Move openshift-lab-origin to redhat-gpte

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/org#403]
Move `openshift-lab-origin` to https://github.com/redhat-gpte

CC @fridim 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@fridim ; to do this, I believe you need someone with permissions in both orgs. is there someone in your team with that? or does someone in the core team already have that? i.e.: @oybed ?

**Comment by garethahealy** [comment]
@fridim @oybed ; this seems to have stalled. still want to do it?

**Comment by sabre1041** [comment]
@garethahealy is this still a valid item to pursue?

**Comment by garethahealy** [comment]
@sabre1041 ; i still think it is, based on previous discussions `openshift-lab-origin` was highlighted as a gpte only repo and didn't come under any CoP activities or contributions.

**Comment by sabre1041** [comment]
Thanks @garethahealy. Closing this task and can reopen if needed
