### ISSUE TITLE
Add Repo ee_utilities

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/org#413]
### Type of repository request
Create Repo ee_utilities, have spoken with Tony Kay in GPTE and he believes we should make it a collection on its own, Playbooks that are useful in doing EE tasks and looking inside. A planned role to do a diff between one Execution Environment and another useful for documenting what is inside. Currently have a role ready to go that will create Execution environments from a set of var dicts. Hoping to maybe even create an Execution Environment that will be able to make its own execution environment, and would likely store the build CI/CD here.

### Requested name for the repository

ee_utilities

### Repository Description

This ansible collection includes a number of roles and tools which can be useful for managing Ansible Execution Environments.

### Admin Access

sean-m-sullivan

### Write Access

sean-m-sullivan

### Read Access
Everyone?

### Additional details

Also would like the galaxy credential that is in the other tower_config/tower_utilities added to this repo as well.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
1. Repository created
2. `ANSIBLE_GALAXY_APIKEY` added to repository
3. Permissions will be applied by #414
