### ISSUE TITLE
kube-rbac-proxy fork

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#416]
### Type of repository request

Repository fork from:
https://github.com/brancz/kube-rbac-proxy

### Requested name for the repository

kube-rbac-proxy

### Repository Description

will be inherited from the fork

### Admin Access

operator admin team + 
Nick Jordan
njordan@redhat.com

### Additional details

please also create a corresponding quay repo
quay.io/redhat-cop/kube-rbac-proxy

with an account able to push there.
put the account username and password in the repo secrets with the following names:
REGISTRY_USERNAME
REGISTRY_PASSWORD

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by nickjordan** [comment]
> ### Type of repository request
> Repository fork from: https://github.com/brancz/kube-rbac-proxy
> 
> ### Requested name for the repository
> kube-rbac-proxy
> 
> ### Repository Description
> will be inherited from the fork
> 
> ### Admin Access
> operator admin team + Nick Jordan [njordan@redhat.com](mailto:njordan@redhat.com)
> 
> ### Write Access
> ### Read Access
> ### Additional details
> please also create a corresponding quay repo quay.io/redhat-cop/kube-rbac-proxy
> 
> with an account able to push there. put the account username and password in the repo secrets with the following names: REGISTRY_USERNAME REGISTRY_PASSWORD
> 
> Review request:
> 
> cc: @redhat-cop/container-cop-core

**GH handle**: "nickjordan"
**Quay**: "njordan" njordan@redhat.com
