### ISSUE TITLE
new repo: vault-config-operator

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#423]
### Type of repository request

new repo + repo transfer

### Requested name for the repository

vault-config-operator

tranfer from https://github.com/raffaelespazzoli/vault-config-operator

### Repository Description

as set by the repo transfer

### Admin Access

operator admin team

### Write Access

operator admin team

### Read Access

public

### Additional details

please create corresponding quay repo: quay.io/redhat-cop/vault-config-operator
please add the following secrets: 'REGISTRY_USERNAME', 'REGISTRY_PASSWORD' to the repo.
---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@raffaelespazzoli contact me offline to execute the repository transfer

**Comment by sabre1041** [comment]
@raffaelespazzoli `REGISTRY_USERNAME` and `REGISTRY_PASSWORD` have been configured. please add the `COMMUNITY_OPERATOR_PAT` secret as you should now have access to make the necessary changes

**Comment by sabre1041** [comment]
Tasks in this issue have been completed
