### ISSUE TITLE
Identify repositories that have an external dependency (Prow).

### ISSUE THREAD

**Issue by pabrahamsson** [redhat-cop/org#459]
- [x] redhat-cop/container-pipelines
       Tide
- [x] redhat-cop/containers-quickstarts
       Tide + Periodic + Presubmit
- [x] redhat-cop/org
       Tide + Periodic + Presubmit + Postsubmit
- [x] redhat-cop/pipeline-library
       Tide + Presubmit
- [x] redhat-cop/rego-policies
       Tide
- [x] redhat-cop/spring-rest
       Tide

**Comment by garethahealy** [comment]
had a look at the repos and created issues. only one I wasn't sure on was how `container-pipelines` uses the pre-submit hook? cant see the prow config and couldn't work it out from previous PRs

**Comment by pabrahamsson** [comment]
> had a look at the repos and created issues. only one I wasn't sure on was how `container-pipelines` uses the pre-submit hook? cant see the prow config and couldn't work it out from previous PRs

My mistake, no Presubmit for `container-pipelines`, only Tide.

**Comment by garethahealy** [comment]
@pabrahamsson closing as all tasks are completed
