### ISSUE TITLE
vault-config-operator maintainer access

### ISSUE THREAD

**Issue by trevorbox** [redhat-cop/org#462]
### Type of permission change

Type of permissions change that is being requested (Example: Team membership, repository membership)

Repository Membership

### Requested Changes

Description of the changes requested

Merger/Maintainer access for https://github.com/redhat-cop/vault-config-operator 

### Additional details

Any additional information or context to provide for this request.

I am a contributor, helping @raffaelespazzoli further maintain the project. 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by pabrahamsson** [comment]
@sabre1041 @raffaelespazzoli merge privileges to `vault-config-operator` is currently given through the `operators-wg-mergers` team. This team also has admin privileges to all/most other operator repositories. Please advice.

**Comment by raffaelespazzoli** [comment]
@pabrahamsson it is fine by me if trevor gets merge priviliges on all operators.
