### ISSUE TITLE
I get removed and re-added to @redhat-cop organization daily (@trevorbox)

### ISSUE THREAD

**Issue by trevorbox** [redhat-cop/org#464]
### Organization or repository

Issue with the organization or name of the repository

I get removed and immediately re-added to @redhat-cop organization every morning.

### Description of the issue

A clear and concise description of what you need assistance with.

I get the following emails every morning:
[GitHub] You've been removed from the "Red Hat Communities of Practice" organization
[GitHub] @redhat-cop-ci-bot has invited you to join the @redhat-cop organization

### Users or Teams affected

Name of users or teams that are affected by the issue.

@trevorbox 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by trevorbox** [comment]
@pabrahamsson @sabre1041 If you have time, can one of you take a look?

**Comment by sabre1041** [comment]
@trevorbox I see the issue. I'll get a PR in today to correct

**Comment by sabre1041** [comment]
@trevorbox Opened #465 to resolve issue you are facing
