### ISSUE TITLE
Create fedora_desktop repository

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/org#473]
### Type of repository request

creation

### Requested name for the repository

fedora_desktop

### Repository Description

An Ansible collection to provision and configure your Fedora desktop

### Admin Access

automation-cop-mgrs

### Write Access

automation-cop-members

### Read Access

public...

### Additional details

Shall become an external version of the internal fedora-csb-spin (in GitLab)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by ericzolf** [comment]
14 days an no reaction, is this normal?

**Comment by sabre1041** [comment]
Implemented as part of #482
