### ISSUE TITLE
Repository For Quarkus GraphQL Demo Workshop Material

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/org#486]
### Type of repository request

New repository

### Requested name for the repository

quarkus-scalable-graphql-demo

### Repository Description

This is a set of lab instructions, and source code for implementing a GraphQL API using Quarkus+SmallRye GraphQL+Reactive Messaging

### Associated CoP

AppDev

### Admin Access

AppDev-CoP

### Write Access

N/A

### Read Access

Public

### Additional details

N/A

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Closing as per request
