### ISSUE TITLE
Create repo services_catalog_configuration

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/org#489]
### Type of repository request

Create repo.
Will be used to configure Automation Service Catalog - A part of AAP.

### Requested name for the repository

services_catalog_configuration

### Repository Description

This ansible collection includes a number of roles and modules which can be used to configure and manage Ansible Automation Services Catalog as code.

### Associated CoP

automation-cop

### Admin Access

automation-cop-tower-mgrs
automation-cop-mgrs

### Write Access

automation-cop-members

### Read Access

All

### Additional details

Also would like the galaxy credential that is in the other `controller_configuration`, `ah_configuration` added to this repo as well.
See #413 for previous request doing the same thing.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sean-m-sullivan** [comment]
Seconded

**Comment by sabre1041** [comment]
Galaxy token added to repository. Once #490 is integrated, it should be good to go
