### ISSUE TITLE
New repo for ServelessWorkFlow and Decisioning CoP

### ISSUE THREAD

**Issue by pamenon** [redhat-cop/org#495]
### Type of repository request

Whether this request is a creation of a new repository, migration of existing repository, or deletion of a repository

### Requested name for the repository

Name of the repository to create or location of existing repository to migrate.

### Repository Description

Description applied to the newly created repository.

### Associated CoP

The CoP this repository is associated with.

### Admin Access

Name of the team(s) and/or user(s) that should have admin access on the newly created repository.

### Write Access

Name of the team(s) and/or user(s) that should have write access on the newly created repository.

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by pamenon** [comment]
Could you please create a repo called: serverlessworkflow-decisioning-cop.

**Comment by sabre1041** [comment]
@pamenon is this still a valid issue that you would like a new repo?

**Comment by pamenon** [comment]
@sabre1041 No, everything related to this was done, so you can close it. Thanks for your help
