### ISSUE TITLE
Add two members to the tower cop admins

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/org#510]
### Type of modification to a team
Add members to existing team

### Requested name for the team

automation-cop-tower-mgrs

### Team Parent

If applicable, name of the existing team that the newly created team should be part of.

### Membership
@jillr
@cidrblock

### Repositories

The configuration block from the previous team

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Completed via #512
