### ISSUE TITLE
New Team - rh4gsre

### ISSUE THREAD

**Issue by hfenner** [redhat-cop/org#516]
### Type of modification to a team

Creation of a new team

### Requested name for the team
rh4gsre

### Team Description
SRE practices for government

### Team Parent
N/A

### Membership
hfenner - maintainer
hultzj - maintainer
swarren - maintainer

### Repositories

Name of the repositories that this team should be part of. If the user requesting this team is not a member of the referenced repository, provide the name of the user to contact to approve. 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@hfenner do you want to associate any repositories at this time?

**Comment by hfenner** [comment]
Not yet, but we will want to create a repo for this organization after creation.
