### ISSUE TITLE
Please DON'T add me as a member of the redhat-cop organization

### ISSUE THREAD

**Issue by swarren** [redhat-cop/org#534]
I keep getting emails from github claiming that:

@redhat-cop-ci-bot has invited you to join the @redhat-cop organization

I don't believe I should be invited to this org since I'm not a Red Hat employee, nor do I have a clue what redhat-cop is. Can you please fix the bot so it stops inviting me? Thanks.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
was added via this PR:
- https://github.com/redhat-cop/org/commit/56410dbf1f7b5afb0493de60c82d9f9f139d8050

@sabre1041 ; if it wasn't meant to be @swarren - who was meant to be added?
