### ISSUE TITLE
Add team member to Blockchain CoP repo

### ISSUE THREAD

**Issue by RobotSail** [redhat-cop/org#556]
### Type of modification to a team

Add a team member to the [blockchain-cop](https://github.com/redhat-cop/blockchain-cop)

### Requested name for the team

Blockchain-CoP

### Team Description

Description applied to the newly created team.

### Membership

Name of the user(s) and the roles that should be applied (member or maintainer)

We want to add [lgonzal@redhat.com](mailto:lgonzal@redhat.com) as a maintainer of the Blockchain CoP repo.

### Repositories

[blockchain-cop](https://github.com/redhat-cop/blockchain-cop)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@RobotSail can you add the GitHub username of the desired individual

**Comment by RobotSail** [comment]
[neosilicon-redhat](https://github.com/neosilicon-redhat)
