### ISSUE TITLE
Create new repo architecture-cop

### ISSUE THREAD

**Issue by rickgcv** [redhat-cop/org#559]
### Type of repository request
New repository

### Requested name for the repository
architecture-cop

### Repository Description
Repository to share content of the recently created Architecture CoP

### Associated CoP
Architecture CoP

### Admin Access
Ricardo Garcia Cavero (rickgcv), Will Nix

### Write Access

Kenny Peeples, Luka Bac, Mike Battles, Andrew Becker, Cecil Beeland, Thomas Bonds, Iain Boyle, Karl Cama, Tom Creamer, Ben Cushing Robert Cushman, Paul Czarkowski, Andrew Das, Atul Deshpande, Jelke Dijkstra, Shaozhen Ding, Gokhan Diren, Jason Dudash, Michael Epley, Burundi Flecther, Kevin Franklin, Ricardo Garcia Cavero, Hunter Gerlach, Adam Goossens, Stephen Goto, Enrico Guarino, Adrian Hammond, Chris Henderson, Anthony Herr, Kevin Holmes, Thalia Hooker, Andrea Hudson, Eric Lavarde, ByoungHee Lee, Anastasios Lisgaras, Peter Magnaye, David Marcus, Andy Miller, Anne Monaghan-Baker, Robert Munilla, E.G Nadhan, Will Nix, Philip Osip, Christopher Pennel, SIlvio Perez Torres, Adam Pippert, Francisco Ramirez, Mark Salowitz, Valentina Sangalli, Nuno Santos, March Schindler, Rudolf Sequeira, Gbenga Taylor, Vincent Tsugranes, Ramon Villarreal Alcala, Takuya Yamashita, Jiaju Zhang

### Read Access
Same as write access

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@rickgcv would you be able to provide GH handles for these users? I'd like also create a new team called `architecture-cop`

**Comment by garethahealy** [comment]
do all those people need write access? or can they not just raise PRs and the admin's review/merge? just an idea...

**Comment by rickgcv** [comment]
Good point @garethahealy then I think it would be enough with me having write access. Thank you!

**Comment by sabre1041** [comment]
@rickgcv circling back on this request. Given the above conversation, would the following be accurate?

* We can create a new team that manages the CoP - ` architecture-cop`
* We can add you and Will Nix as members. Can you provide Will's GH handle

If all looks good, we can proceed

**Comment by rickgcv** [comment]
@sabre1041 That looks good. Will's GH handle is xunlinkx

Thank you!

**Comment by djdanielsson** [comment]
was this ever completed?

**Comment by garethahealy** [comment]
since this issue is now a full year old and has stalled, closing. if this is still needed @rickgcv - please re-open
