### ISSUE TITLE
config_as_code_workshop Repo request

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/org#562]
### Type of repository request
Create Repo config_as_code_workshop, This will migrate https://github.com/sean-m-sullivan/ansiblefest2022_configuration_as_code
to the cop as it is being used by people as a more official workshop outside of ansiblefest.

### Requested name for the repository

config_as_code_workshop

### Repository Description

 A guided lab with using verified collections utilizing Configuration as Code to maintain your AAP instances

### Admin Access

automation-cop-tower-mgrs

### Write Access

automation-cop-tower-mgrs

### Read Access
Everyone?

### Additional details

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@sean-m-sullivan ; what CoP is going to look after this workshop and is it going to be developed further? or is it done and no further dev is planned on it?

**Comment by sean-m-sullivan** [comment]
@garethahealy Right now its David and I in the Automation COP maintaining it, It is already on demo.redhat.com
https://demo.redhat.com/catalog?item=babylon-catalog-prod/ansiblebu.aap2-workshop-config-as-code.prod&utm_source=webapp&utm_medium=share-link

Its going to be a Lab at Summit/Ansiblefest in May, we just wanted to move it to the COP from my personal repo, the idea is anyone can run it, provided they have a Hub and a Controller to interact with.

**Comment by sean-m-sullivan** [comment]
@garethahealy @oybed any movement on this?
