### ISSUE TITLE
New repo request ==> ansible-snapshot

### ISSUE THREAD

**Issue by heatmiser** [redhat-cop/org#564]
### Type of repository request

New repository request

### Requested name for the repository

ansible-snapshot

### Repository Description

Collection of Ansible roles for performing snapshot/backup/revert related activities across systems, infrastructure, and cloud.

### Admin Access

Mike Savage @heatmiser
Bob Mader @swapdisk
David Danielsson @djdanielsson
Jeff Cutter @jeffmcutter

### Write Access

Mike Savage @heatmiser
Bob Mader @swapdisk
David Danielsson @djdanielsson
Jeff Cutter @jeffmcutter

### Read Access

World readable

### Additional details

This to be a utility collection created to work hand in hand with Leapp collection being developed at https://github.com/oamg/ansible-leapp ...as well as for other projects needing automated snapshot-related capabilities

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@heatmiser apologies for the delay here. To simplify things, it would be good to create a team as well so that permissions can be allocated given the write and admin access levels are the same. Do you have a preferred team name that should also be created?

**Comment by heatmiser** [comment]
@sabre1041 Please create a team named `ansible-snapshot-admins`

Admin Access (revised)
Mike Savage @heatmiser
Bob Mader @swapdisk

**Comment by sabre1041** [comment]
Team created and associated with [ansible-snapshot](https://github.com/redhat-cop/ansible-snapshot) repository

**Comment by sabre1041** [comment]
Completed via #566
