### ISSUE TITLE
Create initial repos and teams for SAP CoP

### ISSUE THREAD

**Issue by makentenza** [redhat-cop/org#57]
### Type of repository request

This initial repository will be initialized with the content of the following repo: https://github.com/miminar/sdh-helpers

### Requested name for the repository

sap-datahub

### Repository Description

Utilities and helpers for SAP Data Hub deployment in OpenShift

### Admin Access

sdh-admins

### Write Access

sdh-mergers

### Read Access

NONE

### Additional details

Additionally create the following team structure under redhat-cop Org:

- sap-cop
    - sdh
        - sdh-admins (makentenza, miminar)
        - sdh-mergers (makentenza, miminar)
    - ansible
        - ansible-admins (makentenza, rhmk)
        - ansible-mergers (makentenza, rhmk)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
@makentenza repo has been created (imported from the other repo you provided) and permissions are being processed. Give it a bit of time and you should be good to go.

https://github.com/redhat-cop/sap-datahub
