### ISSUE TITLE
[RFE] Enable discussions

### ISSUE THREAD

**Issue by cidrblock** [redhat-cop/org#573]
Can we enable discussions to capture details about reoccurring processes such as:

- permission changes/requests
- repository migrations

It may not prevent all new issues related to these, but it might save someone typing in the future and would allow for a place to capture some information for future reference

**Comment by djdanielsson** [comment]
why not just require that if someone wants to modify an already created repo/user perms that they have to re-open the original issue with the update? seems like it would accomplish the same thing

**Comment by cidrblock** [comment]
How about questions like "How do I migrate a collection to the org?"  This one just cam up today.

**Comment by IPvSean** [comment]
> 

This is what I am curious about.  How do I migrate the https://github.com/network-automation/toolkit to here (since it is a requirement for validated content)

**Comment by djdanielsson** [comment]
@sabre1041 can work with you on migrating it over

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/org/discussions/landing looks enabled. OK to close?
