### ISSUE TITLE
Create team 

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/org#582]
### Type of modification to a team

Whether this request is a creation of a new team or modification of an existing team.

### Requested name for the team

redhat-cop-sre

### Team Description

Red Hat Community of Practice SRE Team

### Team Parent

N/A

### Membership

* @sabre1041 
* @oybed 
* @pabrahamsson 
* @djdanielsson 
* @etsauer
* @garethahealy 
* @JaredBurck 

### Repositories

* [org](https://github.com/redhat-cop/org)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
@sabre1041 resolved by https://github.com/redhat-cop/org/pull/583?

**Comment by sabre1041** [comment]
@oybed yup. Closing
