### ISSUE TITLE
Create cloud.gcp_ops repository

### ISSUE THREAD

**Issue by gravesm** [redhat-cop/org#585]
### Type of repository request

New repository

### Requested name for the repository

cloud.gcp_ops

### Repository Description

Ansible roles for managing GCP resources

### Associated CoP

Automation

### Admin Access

automation-cop-tower-mgrs

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by djdanielsson** [comment]
it has been updated that validated content have their own team which is now validated-content-curators instead of using automation-cop-tower-mgrs

**Comment by djdanielsson** [comment]
this has been created
