### ISSUE TITLE
Please move ansible-collections/edge.microshift to redhat-cop/edge.microshift

### ISSUE THREAD

**Issue by maxamillion** [redhat-cop/org#587]
### Type of repository request
migration of existing repository

### Requested name for the repository
edge.microshift

Name of the repository to create or location of existing repository to migrate.

https://github.com/ansible-collections/edge.microshift/

### Repository Description

Description applied to the newly created repository.

Validated Content collection for Microshift

### Associated CoP

Automation CoP

### Admin Access

Name of the team(s) and/or user(s) that should have admin access on the newly created repository.
maxamillion
resolutecoder
matoval
thom-at-redhat

validated-content-curators

### Write Access

Name of the team(s) and/or user(s) that should have write access on the newly created repository.

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by djdanielsson** [comment]
this has been added
