### ISSUE TITLE
Permissions for must-gather-operator repository

### ISSUE THREAD

**Issue by noseka1** [redhat-cop/org#597]
### Type of permission change

Type of permissions change that is being requested (Example: Team membership, repository membership)

### Requested Changes

I would like to be added as a maintainer of the repo https://github.com/redhat-cop/must-gather-operator. Would like to get write permissions for this repo.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Request was completed
