### ISSUE TITLE
Create SAP automation related repositories for SAP CoP

### ISSUE THREAD

**Issue by makentenza** [redhat-cop/org#60]
### Type of repository request

All the initial repositories we are creating now are repositories that already exist that are moved to Red Hat's SAP CoP, renaming those in some cases

### Requested name for the repository

sap-rhsm --> Actual repository: https://github.com/mk-ansible-roles/subscribe-rhn
sap-hana-hsr --> Actual repository: https://github.com/mk-ansible-roles/saphana-hsr
sap-hostagent --> Actual repository: https://github.com/mk-ansible-roles/sap-hana-hostagent
sap-hana-deployment --> Actual repository: https://github.com/mk-ansible-roles/sap-hana-deployment
sap-hana-mediacheck --> Actual repository: https://github.com/mk-ansible-roles/sap-hana-mediacheck

### Repository Description

sap-rhsm --> Register and subscribe a RHEL Server to RHEL for SAP Solutions related repositories
sap-hana-hsr --> Configures SAP HANA system replication 
sap-hana-hostagent --> Deploys SAP Host Agent on the given hosts
sap-hana-deployment --> Deploys SAP HANA on the given hosts
sap-hana-mediacheck --> Checks for proper installation media for SAP HANA

### Admin Access

ansible-admins

### Write Access

ansible-mergers

### Additional details

Please also add 'tbludau' GitHub user to 'ansible-mergers' team.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by makentenza** [comment]
@sabre1041 any update on this?

**Comment by sabre1041** [comment]
@makentenza the team is continuing to discuss how to handle mass repo imports. Will try to provide an update soon

**Comment by makentenza** [comment]
Ok thanks @sabre1041. We can do the repo content import even if you guys create new empty repos if that helps.

**Comment by oybed** [comment]
@makentenza I don't think the import is the issue, but rather the number of repos this is (including the possibility of additional future repos). Since github doesn't support grouping like gitlab's sub-groups, it's a bit of a challenge on how we best structure this. So, we are wondering if you could may be open to working with us a bit on limiting the number of repos (e.g.: don't use separate repos for each ansible role, etc.)?

**Comment by makentenza** [comment]
Thanks for the update @oybed. So what's the issue with the number of repositories? Why is this a problem? We were trying to follow upstream approach for system roles, one role per repo. Also it will be harder to implement CI later in the repo, but if there is no other option just create one repo called sap-ansible-roles and we'll figure out later how to deal with this. Since there is no sub-groups capabilities for GitHub would it make more sense to create another Org like  redhat-sap-cop or redhat-cop-sap to solve this problem?

**Comment by makentenza** [comment]
@oybed please hold on with this request for now while we discuss internally the direction we want to take with this.

**Comment by makentenza** [comment]
@oybed we can close this issue now, and we can also remove the following repo:

https://github.com/redhat-cop/sap-datahub

**Comment by sabre1041** [comment]
@makentenza would you also like the `sap-cop` team removed or to retain it so that the CoP can be added to other repositories?

**Comment by makentenza** [comment]
Yes, it's fine to remove the team as well @sabre1041

**Comment by sabre1041** [comment]
Removed `sap-datahub` repository

All resources removed
