### ISSUE TITLE
Ansible ZipShip Teams and Repository

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/org#606]
Create the following assets for the Ansible ZipShip effort

### Create Teams

Each of the following teams will include the following users as maintainers

* @A-Beck
* @sabre1041
* @bontreger
* @brady-spiva
* @jeffcpullen
* @kyetter

Top Level Team

* `ansible-zipship`

Subteams

*  `ansible-zipship-mergers`
* `ansible-zipship-admins`

### Organization or repository

Create new `ansible-zipship-images` repository

Associate  `ansible-zipship` with `read` access, `ansible-zipship-admins` with `admin` access and `ansible-mergers` with write access

---

Review request:
isr
cc: @redhat-cop/container-cop-core

**Comment by oybed** [comment]
Done with #607 - closing
