### ISSUE TITLE
create gitops-std-rep

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#614]
### Type of repository request

create new gitops-std-repo

### Requested name for the repository

gitops-std-repo

### Repository Description

this repo contains the standard structure for an OpenShift multi-cluster day2 configuration gitops repo

### Associated CoP

Container or Gitops

### Admin Access

Raffaele Spazzoli, Gerald Nunn

### Write Access

Not sure, none for now.

### Read Access

Anyone

### Additional details

this repo should be of type template

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@raffaelespazzoli a few thoughts and proposals. Let me know what you think:

1. To provide a little more clarity on the repository and its purpose, modify the proposed name to be `gitops-standards-repo-template`
2. For repository management, the CoP org has a existing team called `gitops-wg-mergers`. We can use this team and add you as a member. @gnunn1 is already a member

**Comment by raffaelespazzoli** [comment]
it's fine by me. please go ahead.
