### ISSUE TITLE
Create cloud.terraform_ops repository

### ISSUE THREAD

**Issue by hakbailey** [redhat-cop/org#639]
### Type of repository request

New repository

### Requested name for the repository

cloud.terraform_ops

### Repository Description

Ansible roles to manage resources needed for Terraform integration with AAP

### Associated CoP

Automation

### Admin Access

validated-content-curators

### Additional details

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Completed via #640

**Comment by hakbailey** [comment]
HI @sabre1041 it looks like the new repo that was created has a trailing dash in the name: https://github.com/redhat-cop/cloud.terraform_ops-. Can that be removed?

**Comment by sabre1041** [comment]
@hakbailey Corrected the mistake.

GitHub action run to update the permissions can be found [here](https://github.com/redhat-cop/org/actions/runs/7028599245)
