### ISSUE TITLE
Repo creation for "ocp4 prerequisites validator".

### ISSUE THREAD

**Issue by giofontana** [redhat-cop/org#64]
### Type of repository request

New repository

### Requested name for the repository

Proposed name: **ocp4-prereqs-validator**

### Repository Description

This repo aims to be ansible playbooks and roles to validate if the prerequisites for OCP 4 deployment is ok. The final intention is to validate all prerequisites, such as:
* DNS 
* LBs
* DHCP (if possible)
* Firewall (if possible)
* etc.

An initial version already exists and it is working that validates all DNS entries (A/PTR and SRV records). You can see [in my github](https://github.com/giofontana/ocp4-prereqs-validator) 

### Admin Access

For now just me (giofontana) and anyone else who wants to collaborate with this project

### Write Access

For now just me (giofontana) and anyone else who wants to collaborate with this project

### Read Access

For now just me (giofontana) and anyone else who wants to collaborate with this project

### Additional details

-

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repository created
