### ISSUE TITLE
2FA github enable

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/org#641]
Github is requiring all users to enable 2FA. If you in the below list, GH thinks you've not got it enabled. If you dont enable 2FA, you'll loose permissions to this org.
- https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13

- @abryson-redhat
- @caseyoc
- @ddeno
- @dfwnetman
- @dstockdreher
- @hector-vido
- @jtlnguyen
- @mumeno
- @natelove
- @neosilicon-redhat
- @nunnchops
- @otatman
- @pathfinder-waffle
- @rhvinel
- @thiasant
- @tolarewaju3
- @trv-rpeoples

**Comment by andreahall12** [comment]
Hi, Gareth. You can remove me as I no longer need access. This is my personal email but I do still work for Red Hat.Thanks,Andrea Hall On Nov 29, 2023, at 7:52 AM, Gareth Healy ***@***.***> wrote:﻿
Github is requiring all users to enable 2FA. If you in the below list, GH thinks you've not got it enabled. If you dont enable 2FA, you'll loose permissions to this org.

https://github.blog/2023-03-09-raising-the-bar-for-software-security-github-2fa-begins-march-13


@abaird-rh
@abhijithumbe
@abryson-redhat
@andreahall12
@Arman084
@beelandc
@charles-shaw
@dasong666
@ddeno
@dfwnetman
@dstockdreher
@FWCoder
@gnekic
@gsampaio-rh
@hfenner
@ihsanmokhlisse
@jhawkinsRH
@johnsimcall
@jtlnguyen
@kelaird
@kenwilli
@kyetter
@marciopaiva
@matthew-willis-redhat
@mumeno
@neosilicon-redhat
@nickjordan
@nunnchops
@otatman
@parmstro
@pathfinder-waffle
@ramius345
@samueltauil
@sangeetaraghu
@shah-zobair
@sushilsuresh
@sysmatrix1
@thiasant
@tolarewaju3
@trv-rpeoples
@vdrvergara
@vikassharma437
@welshstew
@robbbbh
@CaseyOC

**Comment by garethahealy** [comment]
MFA will be abled at the end of March. If you've not enabled by then, you'll be removed from this org.

@abryson-redhat
@CaseyOC
@ddeno
@dfwnetman
@dstockdreher
@hector-vido
@jtlnguyen
@mumeno
@NateLove
@neosilicon-redhat
@nunnchops
@otatman
@pathfinder-waffle
@rhvinel
@thiasant
@tolarewaju3
@trv-rpeoples

**Comment by garethahealy** [comment]
2FA will be enabled in a weeks time. As you do not have it enabled, you will be removed from this org. If you wish to stay, please enable 2FA

- @abryson-redhat
- @ddeno
- @dfwnetman
- @dstockdreher
- @jtlnguyen
- @mumeno
- @neosilicon-redhat
- @pathfinder-waffle
- @rhvinel
- @thiasant
- @tolarewaju3
- @trv-rpeoples
- @CaseyOC
- @nunnchops
- @otatman

**Comment by garethahealy** [comment]
2FA enabled.
