### ISSUE TITLE
Create new repo ocpv_lab

### ISSUE THREAD

**Issue by RanabirChakraborty** [redhat-cop/org#668]
### Type of repository request

new repository

### Requested name for the repository

ocpv_lab

### Repository Description

Demonstrating the use of OpenShift Virtualization as an operating environment 
(same as https://github.com/ansible-middleware/ocpv_lab)

### Associated CoP

Infra cop

### Admin Access

Andrew Block ([sabre1041](https://github.com/sabre1041), ablock@redhat.com), Guido Grazioli ([guidograzioli](https://github.com/guidograzioli), ggraziol@redhat.com), Ranabir Chakraborty ([RanabirChakraborty](https://github.com/RanabirChakraborty), rchakrab@redhat.com), Romain Pelisse ([rpelisse](https://github.com/rpelisse), rpelisse@redhat.com), Harsha Cherukuri ([hcherukuri](https://github.com/hcherukuri), hcheruku@redhat.com), Carlo de Wolf ([wolfc](https://github.com/wolfc), cdewolf@redhat.com), Roel Hodzelmans ([RHodzelmans](https://github.com/RHodzelmans), rhodzelm@redhat.com)

### Write Access

Same as Admin access

### Read Access

Same as Admin access

### Additional details

We would like to fork the [ocpv_lab](https://github.com/ansible-middleware/ocpv_lab) repo from ansible-middleware org into the redhat-cop org.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Thanks @RanabirChakraborty We'll add the individuals that you mentioned to the @redhat-cop/validated-content-curators team

**Comment by sabre1041** [comment]
* @guidograzioli
* @RanabirChakraborty
* @rpelisse
* @hcherukuri
* @wolfc
* @RHodzelmans

Would you be able to fill out this quick form?

* https://red.ht/github-redhat-cop-username

**Comment by wolfc** [comment]
Note that we have a tool https://github.com/jboss-set/mjolnir which links and monitors Kerberos and GitHub ids. It might be of interest.
