### ISSUE TITLE
Migration of network.restore to redhat-cop

### ISSUE THREAD

**Issue by KB-perByte** [redhat-cop/org#698]
### Type of repository request
Migration of existing repository
https://github.com/KB-perByte/network.restore

### Requested name for the repository

network.restore

### Repository Description

(Validated Content)
The network.restore enables users to restore configuration to network appliance from a backup.

### Associated CoP

The CoP this repository is associated with.
Ansible Networking

### Admin Access

@KB-perByte @NilashishC @rohitthakur2590 @trishnaguha

### Write Access

@KB-perByte @NilashishC @rohitthakur2590 @trishnaguha

### Read Access

all

### Additional details

N/a 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
This request has been completed per #699
