### ISSUE TITLE
Create a repository for managing devspaces base images

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/org#709]
### Type of repository request

Repository creation

### Requested name for the repository

devspaces-images

### Repository Description

A factory model for managing workspace base images for Red Hat OpenShift Dev Spaces

### Associated CoP

container-cop

### Admin Access

@etsauer @cgruver @natelove

### Read Access

public

### Additional details

We're planning on using this repo to combine our separate efforts to use CEKit as an image layering tool for creating dev spaces images. The repos we plan to merge into this are:

https://github.com/cgruver/dev-workspace-utilities/
https://github.com/etsauer/devspaceify

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@etsauer what are your thoughts of a new nested team under `container-cop`? Maybe a team called `devspaces` with the list of admins that you listed?
