### ISSUE TITLE
Migration of existing repository: oamg/infra.convert2rhel 

### ISSUE THREAD

**Issue by r0x0d** [redhat-cop/org#724]
### Type of repository request

Migration of an existing repository

### Requested name for the repository

[redhat-cop/infra.convert2rhel](https://github.com/oamg/infra.convert2rhel/)

### Repository Description

This collection provides Ansible roles you can use to perform conversion using the Convert2RHEL framework. Use these roles as the foundation of your conversion automation solution.

### Associated CoP

Automation

### Admin Access

[Rodolfo Olivieri](https://github.com/r0x0d) - @r0x0d
[Andrea Waltlová](https://github.com/andywaltlova) - @andywaltlova
validated_content_curators

### Write Access

[Rodolfo Olivieri](https://github.com/r0x0d) - @r0x0d
[Andrea Waltlová](https://github.com/andywaltlova) - @andywaltlova
[David Danielsson](https://github.com/djdanielsson) - @djdanielsson 
[Matej Buocik](https://github.com/matejbuocik)  - @matejbuocik 
[Marek Filip](https://github.com/Wecros) - @Wecros 

### Read Access

All

### Additional details

None.
---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@sabre1041 ; i've sent @r0x0d your way, as he had a question on best way to migrate repo over.

**Comment by sabre1041** [comment]
Thanks @garethahealy. I will work with @r0x0d and take it from there

**Comment by r0x0d** [comment]
Hi, @garethahealy. Me and @sabre1041 migrated the repository to redhat-cop (https://github.com/redhat-cop/infra.convert2rhel), I think we can close this now.
