### ISSUE TITLE
request for a new repository: must-gather-operator

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/org#73]
### Type of repository request

creation.
Name: must-gather-operator

### Requested name for the repository

https://github.com/raffaelespazzoli/must-gather-operator

### Repository Description

An operator to simplify the creation and upload of must-gather information.

### Admin Access

Raffaele Spazzoli

### Read Access

repository should be public

### Additional details

Please create the following:

- gh-pages branch with empty content
- deploy key
- travis integration
- corresponding redhat-cop/must-gather-operator registry
- quay's username and password should be passed as environment variables to travis jobs as: DOCKER_USER, DOCKER_PASSWORD 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@raffaelespazzoli are you ok with the following change to the description:

"An operator to simplify the creation and upload of cluster diagnostics from the must-gather tool"

**Comment by raffaelespazzoli** [comment]
I'm on with it.

**Comment by sabre1041** [comment]
resolved via #75
