### ISSUE TITLE
Add new rhel-migration team

### ISSUE THREAD

**Issue by r0x0d** [redhat-cop/org#739]
### Type of modification to a team
Create a new team.

### Requested name for the team
rhel-migration

### Team Description
This is a team focused on RHEL migrations, mainly for the redhat-cop/infra.convert2rhel repository.

### Team Parent
None

### Membership
**Admin**
[Rodolfo Olivieri](https://github.com/r0x0d) - @r0x0d
[Andrea Waltlová](https://github.com/andywaltlova) - @andywaltlova

**Maintainer**
[Mike Savage](https://github.com/heatmiser) - @heatmiser

**Member**
[David Danielsson](https://github.com/djdanielsson) - @djdanielsson
[Matej Buocik](https://github.com/matejbuocik) - @matejbuocik
[Daniel Fajmon](https://github.com/solumath) - @solumath
[Peter Zdravecký](https://github.com/monnte) - @monnte

### Repositories
https://github.com/redhat-cop/infra.convert2rhel

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by r0x0d** [comment]
@sabre1041 to take care of this in his afternoon

**Comment by solumath** [comment]
@r0x0d 
Marek Filip - Wecros doesn't work in Red Hat anymore

**Comment by r0x0d** [comment]
> @r0x0d Marek Filip - Wecros doesn't work in Red Hat anymore

Thanks!
