### ISSUE TITLE
Enable softwarefactory-project-zuul github app for the redhat-cop org

### ISSUE THREAD

**Issue by GomathiselviS** [redhat-cop/org#740]
### Repository
Validated Content Collection Repos

### Name of integration

softwarefactory-project-zuul github app

### Link to integration website

https://ansible.softwarefactory-project.io/zuul

### Describe what is attempting to be accomplished

The current procedure for the validated content collections involves manual uploading to Automation Hub (AH). To streamline this process and automate it through Zuul, the validated content repositories need to be integrated with Zuul.  For that softwarefactory-project-zuul github app integration must first be established in the redhat-cop organization.

### Additional context for request

Any additional information or context to describe the use case.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@GomathiselviS installed. which repos need access? as there are 24 repos tagged as validated content currently:
- https://github.com/search?q=topic%3Avalidated-content+org%3Aredhat-cop&type=Repositories

And i'd prefer not to enable this org wide.

**Comment by GomathiselviS** [comment]
> @GomathiselviS installed. which repos need access? as there are 24 repos tagged as validated content currently:
> 
> * https://github.com/search?q=topic%3Avalidated-content+org%3Aredhat-cop&type=Repositories
> 
> And i'd prefer not to enable this org wide.

The following repositories need access to the app

https://github.com/redhat-cop/cloud.azure_ops
https://github.com/redhat-cop/cloud.aws_ops
https://github.com/redhat-cop/cloud.aws_troubleshooting
https://github.com/redhat-cop/cloud.terraform_ops
https://github.com/redhat-cop/cloud.gcp_ops
