### ISSUE TITLE
Add k8s_config repository

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#77]
### Type of repository request

Migration of existing repository

### Requested name for the repository

k8s_config

https://github.com/redhat-gpte-devopsautomation/k8s_config

### Repository Description

Ansible role for managing Kubernetes configuration

### Admin Access

Same users as have access to the "babylon" repository.

### Write Access

Same users as have access to the "babylon" repository.

### Read Access

Same users as have access to the "babylon" repository.

### Additional details

The k8s_config repository is part of project babylon and so, at least initially, is managed by the same team.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
resolved per #76
