### ISSUE TITLE
New Repo for OCP 4 on vSphere Hands-on Workshop

### ISSUE THREAD

**Issue by giofontana** [redhat-cop/org#78]
### Type of repository request

New repo to migrate code that is here: https://github.com/giofontana/ocp4-vsphere-workshop.git

### Requested name for the repository

ocp4-vsphere-workshop

### Repository Description

Workshop Hands-on - Deploying OpenShift on vSphere

### Admin Access

giofontana - admin

### Write Access

giofontana

### Read Access

giofontana

### Additional details

This is a workshop I created to train our team on the deployment of OCP 4.2 on vSphere. I suppose that it can be helpful to other teams also.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Hi @giofontana. The CoP team would be happy to work with you to bring this repository in. Please reach out on internal channels and we can work through the next steps

**Comment by sabre1041** [comment]
Repository has been imported
