### ISSUE TITLE
showroom project repository request

### ISSUE THREAD

**Issue by bkaraoren** [redhat-cop/org#782]
### Type of repository request

We are currently started to work in a new project to deploy a standard operating environment fully automated with ansible which we require two repositories on GitHub. 

### Requested name for the repository

showroom-code
showroom-inventory

### Repository Description

showroom-code: A Red Hat Technology based environment suitable for demonstrating a Red Hat opinionated architecture involving automated Standard Operating Environments for Red Hat Enterprise Linux.

showroom-inventory: inventory and variable repository that is used by showroom-code

### Associated CoP

rhis-builder

### Admin Access

Bilhan Karaören <bkaraore@redhat.com>
Manas Maiti <mmaiti@redhat.com>
Mehmet Kutlu <mkutlu@redhat.com>
Yigit Polat <ypolat@redhat.com>

### Write Access

Bilhan Karaören <bkaraore@redhat.com>
Manas Maiti <mmaiti@redhat.com>
Mehmet Kutlu <mkutlu@redhat.com>
Yigit Polat <ypolat@redhat.com>

### Read Access

Bilhan Karaören <bkaraore@redhat.com>
Manas Maiti <mmaiti@redhat.com>
Mehmet Kutlu <mkutlu@redhat.com>
Yigit Polat <ypolat@redhat.com>

### Additional details

We expect the two repositories as private to be created until the code is ready for public access.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@martinwelk @mannyci @yigitpolat I can see in Rover, but not members of the CoP

mkutlu and jocosta need to link their github to rover:
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

**Comment by bkaraoren** [comment]
I have removed Martin and Jose from the repository access, so we can proceed with the creation of repositories.

**Comment by bkaraoren** [comment]
@garethahealy any update on this request?
