### ISSUE TITLE
Creation of a new rhel-bootc-examples repository

### ISSUE THREAD

**Issue by cgwalters** [redhat-cop/org#788]
### Type of repository request

Creation of a new repository

### Requested name for the repository

rhel-bootc-examples

### Repository Description

Examples for rhel-bootc

### Associated CoP

RHEL

### Admin Access

Let's make a small team to start with me and @sabre1041 and we will expand it from there.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by cgwalters** [comment]
Initial other team members

- ckyrouac 
- jeckersb

**Comment by sabre1041** [comment]
Chatted with @cgwalters and the following will be created:

New Teams:

* `bootc` - All included members as initial maintainers. read on `bootc-examples`
  * `bootc-mergers` - All included members as initial maintainers. write on `bootc-examples`

New Repositories
* bootc-examples

Members to add
* @cgwalters
* @ckyrouac
* @jeckersb

**Comment by cgwalters** [comment]
I don't seem to have access to the repository
