### ISSUE TITLE
k8s_config ansible-galaxy integration

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#79]
### Repository

k8s_config

### Name of integration

ansible-galaxy

### Link to integration website

https://galaxy.ansible.com/

### Describe what is attempting to be accomplished

The Ansible role k8s_config should be published to ansible-galaxy under the redhat-cop org.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
https://galaxy.ansible.com/redhat-cop/k8s_config
