### ISSUE TITLE
Request GitHub to Red Hat ID linkage

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/org#791]
To be a member of the Red Hat CoP GitHub organization, you are required to be a Red Hat employee.
Non-employees are invited to be outside-collaborators (https://github.com/orgs/redhat-cop/outside-collaborators).

To resolve GitHub IDs to Red Hat IDs, we check if we can find you via LDAP.

If you are unsure how to set your GitHub ID within LDAP, see:
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

As we have been unable to resolve your GitHub ID via LDAP, can you please add your GitHub handle to Rover:

- [ ] @sbailleu
- [x] @sushilsuresh
- [x] @Chetan-07
- [x] @berkeragir

**Comment by garethahealy** [comment]
@sbailleu @sushilsuresh @Chetan-07 @berkeragir ; if you still work for RH, can you link your github to rover:
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

**Comment by sushilsuresh** [comment]
@garethahealy I don't work for Red Hat any more. Feel free to purge my account 😭

**Comment by berkeragir** [comment]
Hello. I also don't work at Red Hat anymore. Feel free remove me from the organization.

**Comment by garethahealy** [comment]
@sbailleu @Chetan-07 ; are you still Red Hatters? if so, can you link your GitHub IDs to Rover, as per:
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

**Comment by garethahealy** [comment]
looking at linkedin, Chetan-07 has left RH - https://www.linkedin.com/in/cshinde07/
