### ISSUE TITLE
Archive businessautomation-cop repo

### ISSUE THREAD

**Issue by pamenon** [redhat-cop/org#794]
### Type of repository request

Archive of a repository

### Requested name for the repository

businessautomation-cop

### Repository Description

N/A

### Associated CoP

The CoP this repository is associated with Business Automation CoP which was retired.

### Admin Access

Name of the team(s) and/or user(s) that should have admin access on the newly created repository.
        maintainers:
          - erouvas
          - hwurht
          - pamenon

### Write Access

          - erouvas
          - hwurht
          - pamenon

### Read Access
It should be read-only by the public.

### Additional details

Any additional information or context to provide for this request.
We no longer do work/support with the RHPAM tool since it moved to IBM, also the CoP linked to that was retired

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by pamenon** [comment]
Please don't archive before I update the ReadMe page accordingly. I will give an update when this can be archived.

**Comment by pamenon** [comment]
Done all necessaries changes merged to the repo. It can be archived now.

**Comment by garethahealy** [comment]
repo archived and raised PR to remove team as no-longer needed: 
- https://github.com/redhat-cop/org/pull/796
