### ISSUE TITLE
Anarchy quay.io repositories

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#82]
### Repository

https://github.com/redhat-cop/anarchy

### Name of integration

quay.io

### Link to integration website

https://quay.io/organization/redhat-cop

### Describe what is attempting to be accomplished

Have quay.io build anarchy and anarchy runner images similar to the current builds in:

https://quay.io/repository/gpte-devops-automation/anarchy-operator
https://quay.io/repository/gpte-devops-automation/anarchy-runner

There are two image repositories needed:

quay.io/redhat-cop/anarchy

Should build from Dockerfile https://github.com/redhat-cop/anarchy/blob/master/operator/Dockerfile
with context directory `/operator` on branches and tags matching regular expression `v\d.*`

quay.io/redhat-cop/anarchy-runner

Should build from Dockerfile https://github.com/redhat-cop/anarchy/blob/master/anarchy-runner/Dockerfile with context directory `/anarchy-runner` on branches and tags matching `v\d.*`

https://quay.io/repository/redhat-cop/anarchy (context directory /operator)
https://quay.io/repository/redhat-cop/anarchy-runner (context directory /anarchy-runner)

Both repositories should trigger builds off of repository tags matching `v\d+.*`. (New tags on the anarchy repository will use semantic tagging starting with "v").

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repositories created and configured as described. Since the tag pattern is not currently matching any existing tags, no builds were able to be tested.

* https://quay.io/repository/redhat-cop/anarchy-runner
* https://quay.io/repository/redhat-cop/anarchy

**Comment by jkupferer** [comment]
@sabre1041 This tag should have matched, no?
https://github.com/redhat-cop/anarchy/releases/tag/v0.3.7

**Comment by sabre1041** [comment]
@jkupferer had an incorrect regex configuration. Updated and triggered build. Tag pushed to both repos
