### ISSUE TITLE
Request new repo for sharing monitoring scripts used for RHDP with the community

### ISSUE THREAD

**Issue by 9strands** [redhat-cop/org#825]
### Type of repository request

Creation of a new repository

### Requested name for the repository

rhdp-monitoring-scripts

### Repository Description

Scripts for monitoring various components of Red Hat infrastructure.

### Associated CoP

GPTE/RHPDS/RHDP platform (as with agnosticd/babylon/anarchy/etc)

### Admin Access

gpte-admins

### Write Access

gpte

### Read Access

public

### Additional details

These are the scripts that we use to monitor the RHPDS/RHDP infrastructure and which will likely be useful to the rest of the community, for things like basic monitoring OCPvirt.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/rhdp-monitoring-scripts

**Comment by 9strands** [comment]
Thank you, @garethahealy!

I'll start populating with our cop- and/or community-relevant monitoring scripts!
