### ISSUE TITLE
Request to create a new repo for Ansible automation for partner certification workflow

### ISSUE THREAD

**Issue by sumitridhal** [redhat-cop/org#838]
### Type of repository request

its a new repository

### Requested name for the repository

redhat-cop/rhcert-automation

### Repository Description

Ansible automation for partner certification workflow

### Associated CoP

The CoP this repository is associated with.

### Admin Access

sridhal, sudeshmu

### Write Access

sridhal, sudeshmu

### Additional details

We are from partner ecosystem certification team, working on partner certification workflows.
we are working on certification automation workflow to enable partners to certify their CCSP RHEL images. In order to provide an Ansible automation for this requirement, we are currently collaborating with Microsoft. To share this with partners, we need assistance creating a repository under redhat/cop.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sudeshmu** [comment]
Hi Any update on this?

**Comment by garethahealy** [comment]
@sudeshmu and @sridhal ; you are both not members of the CoP - please raise a `Become a Contributor` first:
- https://github.com/redhat-cop/org/issues/new/choose

@sridhal can you also link your github to rover please:
 - https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

**Comment by sumitridhal** [comment]
@garethahealy , this is completed

**Comment by garethahealy** [comment]
- https://github.com/redhat-cop/rhcert-automation
- https://github.com/redhat-cop/org/pull/868
