### ISSUE TITLE
Creation of quay_configuration repo

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/org#842]
### Type of repository request

Creation of new repository

### Requested name for the repository

quay_configuration

### Repository Description

Ansible collection for managing Red Hat Quay

### Associated CoP

automation_cop
container_cop 

### Admin Access

validated-content-curators

Can you also add myself (@Tompage1994 ) and @Herve4m to this group please

### Additional details

We plan to port https://github.com/herve4m/quay-collection into this repository and eventually release the collection as infra.quay_configuration with the intention to get the collection validated and potentially certified.
---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@Tompage1994 OK to close?

**Comment by Tompage1994** [comment]
Yes all is sorted now. Thanks!
