### ISSUE TITLE
Requesting new repository to host openshift-iac blueprint for FlightPath

### ISSUE THREAD

**Issue by rgoodson-redhat** [redhat-cop/org#851]
### Type of repository request

New Repository

### Requested name for the repository

openshift-iac

### Repository Description

FlightPath blueprint for end-to-end automated OpenShift Deployment. This repo includes automation for the dependent IT services, like IP Address management, DNS, and load balancers, option to deploy using either the Agent-based install or Red Hat Advanced Cluster Manager, and GitOps examples for commonDay2 configurations. The goal is for an administrator to define a new cluster in a Git repo and the automation then orchestrates the deployment of a full functional, ready to consume OpenShift cluster.

### Associated CoP

FlightPath / OpenShift CoP

### Admin Access

Piotr Kliczewski
Sal Erlahal
Ryan Goodson

### Write Access

David Dreggors
John Force
Brandon Marlow
Ondra Machacek

### Read Access

Default

### Additional details

This effort will consolidate a number of other repos and efforts across Red Hat to support the declarative deployment of OpenShift.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@rgoodson-redhat ; can you provide the github IDs of those people mentioned? and if they've not already, ask them to join the CoP and link their GH to RH accounts via rover.

**Comment by rgoodson-redhat** [comment]
Ryan Goodson - rgoodson-redhat

Piotr Kliczewski - pkliczewski

Sal Erlahal - selrahal

David Dreggors - ddreggors

Brandon Marlow - bmarlow

Ondra Machacek - machacekondra

James Force - jforce

Bob Mader - swapdisk


Regards,



Ryan Goodson

Red Hat Customer Engineering

***@***.***
M: 903-312-1557
<https://red.ht/sig>

UPCOMING TRAVEL:
NONE

UPCOMING TRAINING:
NONE

UPCOMING TIME OFF:
Aug 23, 2024 - Red Hat Recharge Day
Sept 2, 2024 - Labor Day
Nov 28 - 29, 2024 - Thanksgiving
Dec 24, 2024 - Christmas Eve
Dec 25, 2024 - Christmas Day
Dec 26 - 31, 2024 - Red Hat End of Year Recharge

**Comment by garethahealy** [comment]
need to accept the invitation (check your email that GH is registered against):
@rgoodson-redhat @selrahal @ddreggors @bmarlow

not part of CoP:
@pkliczewski

part of CoP and good to go:
@jforce @machacekondra @swapdisk

**Comment by rgoodson-redhat** [comment]
I accepted the invite two weeks ago. Is it still not showing up for you?

Regards,



Ryan Goodson

Red Hat Customer Engineering

***@***.***
M: 903-312-1557
<https://red.ht/sig>

UPCOMING TRAVEL:
NONE

UPCOMING TRAINING:
NONE

UPCOMING TIME OFF:
Aug 23, 2024 - Red Hat Recharge Day
Sept 2, 2024 - Labor Day
Nov 28 - 29, 2024 - Thanksgiving
Dec 24, 2024 - Christmas Eve
Dec 25, 2024 - Christmas Day
Dec 26 - 31, 2024 - Red Hat End of Year Recharge

**Comment by garethahealy** [comment]
<img width="988" alt="Screenshot 2024-08-01 at 21 34 54" src="https://github.com/user-attachments/assets/3de477eb-6804-496d-a4f6-a145afe6841a">

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/openshift-iac

**Comment by rgoodson-redhat** [comment]
Awesome, thank you sir!

Regards,

Ryan Goodson
Red Hat
***@***.***
Mobile: 903-312-1557
