### ISSUE TITLE
Please add me as a member of the automation-cop-members list

### ISSUE THREAD

**Issue by adonisgarciac** [redhat-cop/org#866]
### Type of permission change

Team membership

### Requested Changes

I'd like to be added to automation-cop-members list

### Additional details

I'm a contributor of redhat-cop/controller-configuration and one of the owners of filetree-* roles. I'd like to be member of automation-cop-members list to be able to review PR and accept them when are related to filetree-* roles.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@adonisgarciac ; you need to accept the CoP membership invitation first. below is showing as you've not accepted:
- https://github.com/orgs/redhat-cop/people/pending_invitations

**Comment by adonisgarciac** [comment]
Done! @garethahealy

**Comment by adonisgarciac** [comment]
yes! thanks
