### ISSUE TITLE
Anarchy test quay.io repository

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#87]
### Repository

https://github.com/redhat-cop/anarchy

### Name of integration

quay.io

### Link to integration website

https://quay.io/organization/redhat-cop

### Describe what is attempting to be accomplished

This request is to build the Anarchy test server similar to the other builds in this previous issue:

https://github.com/redhat-cop/org/issues/82

Like the builds in the previous issue, this request is for building the Anarchy test server, a mock-up of communication with Babylon Dark-Tower.

The current quay.io repository for this image is at:

https://quay.io/repository/gpte-devops-automation/anarchy-operator-test-server

The new image repository should be:

quay.io/redhat-cop/anarchy-test-server

The image should build from Dockerfile https://github.com/redhat-cop/anarchy/blob/master/test/server/Dockerfile
with context directory /test/server and build onbranches and tags matching regular expression `v\d.*`

https://quay.io/repository/redhat-cop/anarchy-test-server (context directory /test/server)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Request Completed
