### ISSUE TITLE
depreciate some collections in galaxy.ansible.com

### ISSUE THREAD

**Issue by djdanielsson** [redhat-cop/org#872]
We recently noticed that some collections that we had depreciated in the old galaxy are no longer showing depreciated once everything was moved to the new galaxy. We would like to try and get those to show depreciated again.

- redhat_cop.controller_configuration
- redhat_cop.aap_utilities
- redhat_cop.ee_utilities
- redhat_cop.ah_configuration

**Comment by garethahealy** [comment]
@sabre1041 or @oybed sound like the people that would have perms to help with that

**Comment by sabre1041** [comment]
Requested collections have been marked as deprecated
