### ISSUE TITLE
Poolboy quay.io integration

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#92]
### Repository

https://github.com/redhat-cop/poolboy

### Name of integration

quay.io

### Link to integration website

https://quay.io/organization/redhat-cop

### Describe what is attempting to be accomplished

Have quay.io build anarchy and anarchy runner images similar to the current builds in:

https://quay.io/repository/gpte-devops-automation/poolboy

There is a single image repositories needed:

quay.io/redhat-cop/poolboy

This image should build from Dockerfile using:

https://github.com/redhat-cop/poolboy/blob/master/operator/Dockerfile

with context directory /operator on branches and build on new tags tags matching regular expression `v\d.*` to produce images:

https://quay.io/repository/redhat-cop/poolboy

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by etsauer** [comment]
@jkupferer I created an empty repository at https://quay.io/repository/redhat-cop/poolboy and a robot account, which I plugged into your repo. You should be able to follow the doc below to configure auto-publishing:

https://redhat-cop.github.io/ci/publishing-images.html

**Comment by sabre1041** [comment]
@jkupferer Is there any more steps that need to be taken at this point?

**Comment by jkupferer** [comment]
This is complete now. Closing issue.
