### ISSUE TITLE
rename rhis team

### ISSUE THREAD

**Issue by bkaraoren** [redhat-cop/org#924]
### Type of modification to a team

We want the existing team to be renamed from "rhis-builder-admins" to "rhis-code-admins"

### Requested name for the team

```
rhis-code-admins
```

### Team Description

Administrative Steering Committee for the RHIS Code

### Membership

@bkaraoren 
@heatmiser 
@mannyci 
@mhjacks 
@mmtktl 
@mwelk-rh
@parmstro 
@yigitpolat 
@techuser-github-rhis

### Repositories

rhis-code
rhis-inventory

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@bkaraoren ; why do you want the name change? it's just an internal name...

**Comment by bkaraoren** [comment]
Hi @garethahealy , just for the alignment with the project. We want to ensure that rhis-code-admin team is directly related to the rhis-code not rhis-builder.

**Comment by garethahealy** [comment]
@bkaraoren ; am abit confused. the PR (https://github.com/redhat-cop/org/pull/811) created those repos as `showroom-code` and `showroom-inventory `, but those repos no longer exist in the org so wont have the correct team membership applied.

have you manually renamed them?

**Comment by bkaraoren** [comment]
yes, renamed the repos but not the team name.

**Comment by garethahealy** [comment]
@bkaraoren please dont rename repos/teams/manually change permissions etc. All of that is controlled by the automation in this repo. if you manually change things, stuff breaks:
- https://github.com/redhat-cop/org/actions/runs/11285769108/job/31389093998
