### ISSUE TITLE
Create OpenShift IaC Landing Zones repo

### ISSUE THREAD

**Issue by selrahal** [redhat-cop/org#933]
### Type of repository request

Create new repo

### Requested name for the repository

openshift-iac-landing-zones

### Repository Description

This repository shows a few examples of the declarative configuration, using the OpenShift IaC framework, for clusters such as Virt landing zones, AI workloads, general purpose, etc....

### Associated CoP

The CoP this repository is associated with.

### Admin Access

@rgoodson-redhat
@selrahal
@pkliczewski

### Write Access

@machacekondra
@ddreggors
@bmarlow
@raffaelespazzoli

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Resolved by #934
