### ISSUE TITLE
New Validated content for infra.windows_ops

### ISSUE THREAD

**Issue by p3ck** [redhat-cop/org#935]
### Type of repository request

New Repository

### Requested name for the repository

infra.windows_ops

### Repository Description

Ansible Roles for managing Windows Resources

### Associated CoP

Automation CoP

### Admin Access

validated-content-curators

### Write Access

validated-content-curators

### Read Access

validated-content-curators

### Additional details

This will also hold Automation Experiences for the next AAP release

The following should be members of the validated-content-curators if not already.
[shahargolshani](https://github.com/shahargolshani)
[ronger4](https://github.com/ronger4)
[p3ck](https://github.com/p3ck)
[Yaish25491](https://github.com/Yaish25491)

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by mhjacks** [comment]
I think this should be instead named infra.windows_ops as the initial use cases are very operationally focused (patching, start/stop services, and setup IIS). infra.windows might be too generic

**Comment by p3ck** [comment]
> I think this should be instead named infra.windows_ops as the initial use cases are very operationally focused (patching, start/stop services, and setup IIS). infra.windows might be too generic

I updated the request to include _ops.  Thanks Martin

**Comment by garethahealy** [comment]
@shahargolshani @ronger4 are not part of the CoP and haven't linked their GH to Rover:
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

@Yaish25491 isn't part of the CoP

**Comment by sabre1041** [comment]
Resolved via #941

**Comment by p3ck** [comment]
I see the repo is created...  But I'm not able to initialize it..

**Comment by sabre1041** [comment]
@p3ck can you confirm access now that the automation has completed and the policies have been applied?

**Comment by p3ck** [comment]
Yes,

Thank you.  All set now
