### ISSUE TITLE
New babylon-events-console repository

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#94]
### Type of repository request

creation of a new repository

### Requested name for the repository

babylon-events-console

### Repository Description

A simple console for running labs on Babylon infrastructure for events such as Red Hat Summit.

### Admin Access

Same access as the babylon repository.

### Write Access

Same access as the babylon repository.

### Read Access

Same access as the babylon repository.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
https://github.com/redhat-cop/babylon-events-console
