### ISSUE TITLE
babylon-events-console quay.io integration

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/org#98]
### Repository

https://github.com/redhat-cop/babylon-events-console

### Name of integration

quay.io with GitHub actions

### Link to integration website

https://quay.io/organization/redhat-cop

### Describe what is attempting to be accomplished

Similar to how the poolboy repository is configured, we would like this repository to build and push images using GitHub actions to quay.io within the redhat-cop org.

We can provide the `.github/workflows/quay.yaml` configuration through a pull request.

For this issue we need the quay.io repository created for babylon-events-console and the secrets QUAY_USERNAME and QUAY_PASSWORD set for use by GitHub actions on the babylon-events-console github repository.

### Additional context for request

This configuration will be similar to this previous issue:

https://github.com/redhat-cop/org/issues/92

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
Repository created: https://quay.io/repository/redhat-cop/babylon-events-console

Secrets added to GitHub repository
